-- =============================================================
-- Auto-gerado por scripts/sync-strings.js em 2026-05-07T19:25:44.151Z
-- 96 strings extraídas
-- =============================================================

-- Insere strings novas e atualiza pt_br das existentes (canônico = código).
insert into public.i18n_strings (chave, pagina, categoria, visibilidade, descricao, pt_br) values
  ('compromissos.descricao', 'compromissos', 'ui', 'usuario', 'Auto-extraído de compromissos.html', 'Suas entradas e saídas recorrentes. Organizadas em Categorias e Subcategorias.'),
  ('compromissos.empty.titulo', 'compromissos', 'sistema', 'usuario', 'Auto-extraído de compromissos.html', 'Nenhum compromisso cadastrado'),
  ('compromissos.titulo', 'compromissos', 'sistema', 'usuario', 'Auto-extraído de compromissos.html', 'Compromissos'),
  ('compromissos.toast.valor_atualizado', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos.js', 'Valor atualizado'),
  ('compromissos.toast.valor_inalterado', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos.js', 'O valor não mudou'),
  ('compromissos.validacao.categoria_obrigatoria', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos.js', 'Escolha uma categoria'),
  ('compromissos.validacao.data_inicio', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos.js', 'Informe a data de início'),
  ('compromissos.validacao.tipo_obrigatorio', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos.js', 'Escolha o tipo'),
  ('compromissos.validacao.valor_invalido', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos.js', 'Informe um valor válido'),
  ('compromissos.validacao.valor_maior_zero', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos.js', 'Informe um valor maior que zero'),
  ('contas.descricao', 'contas', 'ui', 'usuario', 'Auto-extraído de contas.html', 'Bancos, cartões, carteiras e investimentos. Alimenta as demais telas.'),
  ('contas.empty.mensagem', 'contas', 'ui', 'usuario', 'Auto-extraído de contas.html', 'Cadastre seu primeiro banco, cartão ou carteira pra começar a controlar suas finanças.'),
  ('contas.empty.titulo', 'contas', 'sistema', 'usuario', 'Auto-extraído de contas.html', 'Nenhuma conta cadastrada'),
  ('contas.titulo', 'contas', 'sistema', 'usuario', 'Auto-extraído de contas.html', 'Contas'),
  ('contas.toast.erro_carregar', 'contas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/contas.js', 'Erro ao carregar contas'),
  ('contas.validacao.desde_obrigatorio', 'contas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/contas.js', 'Informe a data inicial (Desde)'),
  ('contas.validacao.dia_fechamento', 'contas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/contas.js', 'Informe o dia de fechamento da fatura (1–31)'),
  ('contas.validacao.nome_obrigatorio', 'contas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/contas.js', 'Informe o nome do banco/cartão'),
  ('dividas.btn_nova', 'dividas', 'ui', 'usuario', 'Auto-extraído de dividas.html', 'Nova dívida'),
  ('dividas.descricao', 'dividas', 'ui', 'usuario', 'Auto-extraído de dividas.html', 'Acompanhe dívidas ativas, em negociação e quitadas com barras de progresso.'),
  ('dividas.eyebrow', 'dividas', 'ui', 'usuario', 'Auto-extraído de dividas.html', 'Controle'),
  ('dividas.modal.label.credor', 'dividas', 'modal', 'usuario', 'Auto-extraído de dividas.html', 'Credor'),
  ('dividas.modal.label.nome', 'dividas', 'modal', 'usuario', 'Auto-extraído de dividas.html', 'Nome da dívida *'),
  ('dividas.modal.placeholder.credor', 'dividas', 'modal', 'usuario', 'Auto-extraído de dividas.html', 'Buscar contato ou digitar novo nome…'),
  ('dividas.modal.placeholder.nome', 'dividas', 'modal', 'usuario', 'Auto-extraído de dividas.html', 'Ex: Financiamento carro'),
  ('dividas.titulo', 'dividas', 'sistema', 'usuario', 'Auto-extraído de dividas.html', 'Dívidas'),
  ('dividas.toast.arquivada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Dívida arquivada (movida para Terminado)'),
  ('dividas.toast.atualizada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Dívida atualizada'),
  ('dividas.toast.categoria_nao_encontrada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Categoria "Dívidas" não encontrada — vá em Configurações para criá-la antes.'),
  ('dividas.toast.criada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Dívida cadastrada'),
  ('dividas.toast.erro_arquivar', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao arquivar'),
  ('dividas.toast.erro_carregar', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao carregar dívidas'),
  ('dividas.toast.erro_excluir', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao excluir'),
  ('dividas.toast.erro_restaurar', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao restaurar'),
  ('dividas.toast.erro_salvar', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao salvar'),
  ('dividas.toast.excluida', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Dívida excluída'),
  ('dividas.toast.taxa_atualizada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Taxa atualizada'),
  ('dividas.toast.todas_parcelas_pagas', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Todas as parcelas já foram pagas'),
  ('dividas.validacao.conta_obrigatoria', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Selecione a conta debitada — pagamento sempre é registrado em Transações.'),
  ('dividas.validacao.data_inicio', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe a data de início'),
  ('dividas.validacao.data_pagamento', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe a data de pagamento'),
  ('dividas.validacao.desconto_excede', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Desconto não pode exceder o total de juros'),
  ('dividas.validacao.nome_obrigatorio', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe o nome da dívida'),
  ('dividas.validacao.nova_taxa', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe a nova taxa'),
  ('dividas.validacao.parcelas_obrigatorias', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe o número de parcelas'),
  ('dividas.validacao.regime_sem_parcelas', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Regime selecionado — informe o número de parcelas.'),
  ('dividas.validacao.valor_total', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe um valor total válido'),
  ('dividas.validacao.vigencia', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe a data de vigência'),
  ('global.btn.cancelar', 'global', 'ui', 'usuario', 'Auto-extraído de investimentos.html', 'Cancelar'),
  ('global.btn.fechar', 'global', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Fechar'),
  ('global.btn.salvar', 'global', 'ui', 'usuario', 'Auto-extraído de investimentos.html', 'Salvar'),
  ('investimentos.btn.novo', 'investimentos', 'ui', 'usuario', 'Auto-extraído de investimentos.html', '+ Novo projeto'),
  ('investimentos.descricao', 'investimentos', 'ui', 'usuario', 'Auto-extraído de investimentos.html', 'Cada projeto é uma meta. Compromissos do grupo Investimentos podem ser atrelados a um projeto.'),
  ('investimentos.empty.btn', 'investimentos', 'ui', 'usuario', 'Auto-extraído de investimentos.html', '+ Criar primeiro projeto'),
  ('investimentos.empty.titulo', 'investimentos', 'sistema', 'usuario', 'Auto-extraído de investimentos.html', 'Nenhum projeto ainda'),
  ('investimentos.titulo', 'investimentos', 'sistema', 'usuario', 'Auto-extraído de investimentos.html', 'Investimentos'),
  ('investimentos.toast.atualizado', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Projeto atualizado'),
  ('investimentos.toast.criado', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Projeto criado'),
  ('investimentos.toast.criado_com_compromisso', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Projeto criado e compromisso vinculado'),
  ('investimentos.toast.erro_carregar', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Erro ao carregar projetos'),
  ('investimentos.toast.saldo_atualizado', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Saldo inicial atualizado'),
  ('investimentos.toast.schema_desatualizado', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Schema desatualizado. Rode a migration 0016 + 0017 no Supabase.'),
  ('investimentos.validacao.aporte_obrigatorio', 'investimentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/investimentos.js', 'Informe o valor do aporte do compromisso'),
  ('investimentos.validacao.categoria_obrigatoria', 'investimentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/investimentos.js', 'Selecione uma categoria para o compromisso'),
  ('investimentos.validacao.data_aporte_obrigatoria', 'investimentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/investimentos.js', 'Informe a data do primeiro aporte'),
  ('investimentos.validacao.nome_obrigatorio', 'investimentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/investimentos.js', 'Informe o nome do projeto'),
  ('minha.chave', 'minha', 'ui', 'usuario', 'Auto-extraído de src/js/lib/textos.js', 'Texto pt-BR'),
  ('nav.dividas', 'nav', 'ui', 'usuario', 'Auto-extraído de dividas.html', 'Dívidas'),
  ('orcamento.descricao', 'orcamento', 'ui', 'usuario', 'Auto-extraído de orcamento.html', 'Visão financeira mensal — gerada automaticamente a partir dos seus compromissos. Edite valores específicos sem alterar a configuração base.'),
  ('orcamento.titulo', 'orcamento', 'sistema', 'usuario', 'Auto-extraído de orcamento.html', 'Orçamento Geral'),
  ('orcamento.toast.erro_gerar', 'orcamento', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/orcamento.js', 'Erro ao gerar orçamento'),
  ('orcamento.validacao.valor_invalido', 'orcamento', 'ui', 'usuario', 'Auto-extraído de src/js/pages/orcamento.js', 'Valor inválido'),
  ('pagamentos.btn.salvar_observacao', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Salvar observação'),
  ('pagamentos.descricao', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Controle do que foi pago no mês. Marque status e registre o valor real efetivamente pago.'),
  ('pagamentos.empty.btn', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Ir para Compromissos'),
  ('pagamentos.empty.mensagem', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Cadastre compromissos ativos pra começar a registrar pagamentos. Pagamentos são gerados automaticamente a partir do orçamento.'),
  ('pagamentos.empty.titulo', 'pagamentos', 'sistema', 'usuario', 'Auto-extraído de pagamentos.html', 'Nenhum pagamento neste mês'),
  ('pagamentos.titulo', 'pagamentos', 'sistema', 'usuario', 'Auto-extraído de pagamentos.html', 'Pagamentos'),
  ('pagamentos.toast.erro_limpar', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Erro ao limpar pagamentos'),
  ('pagamentos.toast.erro_marcar_pago', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Erro ao marcar como pago'),
  ('pagamentos.toast.limpos', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Pagamentos pendentes limpos. Regenerando…'),
  ('pagamentos.toast.marcado_pago', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Marcado como pago'),
  ('pagamentos.toast.regenerados', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Blocos regenerados'),
  ('pagamentos.toast.schema_desatualizado', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Schema desatualizado. Rode a migration 0011 no Supabase pra blocos dinâmicos.'),
  ('pagamentos.validacao.data_inicio', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/pagamentos.js', 'Informe a data de início'),
  ('pagamentos.validacao.valor_invalido', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/pagamentos.js', 'Valor inválido'),
  ('transacoes.descricao', 'transacoes', 'ui', 'usuario', 'Auto-extraído de transacoes.html', 'Registro real do dinheiro que entrou e saiu — diferente do orçamento (planejado) e dos pagamentos (status mensal).'),
  ('transacoes.empty.btn', 'transacoes', 'ui', 'usuario', 'Auto-extraído de transacoes.html', '+ Nova transação'),
  ('transacoes.empty.mensagem', 'transacoes', 'ui', 'usuario', 'Auto-extraído de transacoes.html', 'Registre a primeira transação para começar seu diário financeiro.'),
  ('transacoes.empty.titulo', 'transacoes', 'sistema', 'usuario', 'Auto-extraído de transacoes.html', 'Nenhuma transação ainda'),
  ('transacoes.titulo', 'transacoes', 'sistema', 'usuario', 'Auto-extraído de transacoes.html', 'Transações'),
  ('transacoes.toast.erro_carregar', 'transacoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/transacoes.js', 'Erro ao carregar transações'),
  ('transacoes.toast.erro_excluir', 'transacoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/transacoes.js', 'Erro ao excluir'),
  ('transacoes.toast.reconciliada', 'transacoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/transacoes.js', 'Transação reconciliada'),
  ('transacoes.validacao.datas_obrigatorias', 'transacoes', 'ui', 'usuario', 'Auto-extraído de src/js/pages/transacoes.js', 'Informe as duas datas do período'),
  ('transacoes.validacao.datas_ordem', 'transacoes', 'ui', 'usuario', 'Auto-extraído de src/js/pages/transacoes.js', 'Data de início deve ser anterior ao fim')
on conflict (chave) do update
  set pt_br      = excluded.pt_br,
      pagina     = excluded.pagina,
      categoria  = excluded.categoria,
      updated_at = now();
