-- =============================================================
-- Auto-gerado por scripts/sync-strings.js em 2026-05-07T23:25:02.712Z
-- 349 strings extraídas
-- =============================================================

-- Insere strings novas e atualiza pt_br das existentes (canônico = código).
insert into public.i18n_strings (chave, pagina, categoria, visibilidade, descricao, pt_br) values
  ('academia.descricao', 'academia', 'ui', 'usuario', 'Auto-extraído de academia.html', 'Tutoriais completos de cada tela, como ela funciona e como se conecta com o restante do sistema.'),
  ('academia.placeholder.busca', 'academia', 'ui', 'usuario', 'Auto-extraído de academia.html', 'Buscar tutorial…'),
  ('academia.titulo', 'academia', 'sistema', 'usuario', 'Auto-extraído de academia.html', 'Academia FinFlow'),
  ('admin.feedback.descricao', 'admin', 'ui', 'usuario', 'Auto-extraído de admin-feedback.html', 'Triagem, trabalho em andamento e arquivo — cada um com a ferramenta certa pro tamanho.'),
  ('admin.feedback.titulo', 'admin', 'sistema', 'usuario', 'Auto-extraído de admin-feedback.html', 'Gerenciar feedback'),
  ('admin.feedback.toast.excluido', 'admin', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/admin-feedback.js', 'Excluído.'),
  ('admin.feedback.toast.salvo', 'admin', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/admin-feedback.js', 'Salvo.'),
  ('admin.feedback.toast.vinculado_changelog', 'admin', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/admin-feedback.js', 'Vinculado ao changelog.'),
  ('admin.idiomas.descricao', 'admin', 'ui', 'usuario', 'Auto-extraído de admin-i18n.html', 'Gerencie as traduções da interface do FinFlow em PT-BR, EN, ES e FR.'),
  ('admin.idiomas.toast.string_criada', 'admin', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/admin-i18n.js', 'String criada.'),
  ('admin.idiomas.validacao.chave_obrigatoria', 'admin', 'ui', 'usuario', 'Auto-extraído de src/js/pages/admin-i18n.js', 'Chave é obrigatória.'),
  ('admin.idiomas.validacao.csv_invalido', 'admin', 'ui', 'usuario', 'Auto-extraído de src/js/pages/admin-i18n.js', 'CSV vazio ou formato inválido.'),
  ('admin.usuarios.descricao', 'admin', 'ui', 'usuario', 'Auto-extraído de admin-usuarios.html', 'Todos os usuários cadastrados no FinFlow, planos e informações de perfil.'),
  ('admin.usuarios.toast.plano_atualizado', 'admin', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/admin-usuarios.js', 'Plano atualizado.'),
  ('compromissos.descricao', 'compromissos', 'ui', 'usuario', 'Auto-extraído de compromissos.html', 'Suas entradas e saídas recorrentes. Organizadas em Categorias e Subcategorias.'),
  ('compromissos.empty.titulo', 'compromissos', 'sistema', 'usuario', 'Auto-extraído de compromissos.html', 'Nenhum compromisso cadastrado'),
  ('compromissos.titulo', 'compromissos', 'sistema', 'usuario', 'Auto-extraído de compromissos.html', 'Compromissos'),
  ('compromissos.toast.atualizado', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Compromisso atualizado'),
  ('compromissos.toast.criado', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Compromisso criado'),
  ('compromissos.toast.deletado', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Compromisso deletado permanentemente'),
  ('compromissos.toast.erro_carregar_categorias', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos.js', 'Erro ao carregar categorias'),
  ('compromissos.toast.erro_categoria_default', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos.js', 'Erro ao criar categorias default'),
  ('compromissos.toast.erro_criar_projeto', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos.js', 'Erro ao criar projeto'),
  ('compromissos.toast.salvo', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Compromisso salvo'),
  ('compromissos.toast.valor_atualizado', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Valor atualizado'),
  ('compromissos.toast.valor_inalterado', 'compromissos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/compromissos/save.js', 'O valor não mudou'),
  ('compromissos.validacao.cat_obrigatoria', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Escolha uma categoria'),
  ('compromissos.validacao.categoria_obrigatoria', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Escolha uma categoria'),
  ('compromissos.validacao.data_inicio', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Informe a data de início'),
  ('compromissos.validacao.nome_obrigatorio', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Informe o nome do compromisso'),
  ('compromissos.validacao.tipo_obrigatorio', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Escolha o tipo'),
  ('compromissos.validacao.valor_invalido', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Informe um valor válido'),
  ('compromissos.validacao.valor_maior_zero', 'compromissos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/compromissos/save.js', 'Informe um valor maior que zero'),
  ('configuracoes.toast.cat_atualizada', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Categoria atualizada'),
  ('configuracoes.toast.cat_com_historico', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Esta categoria tem histórico vinculado. Marque "Mover mesmo assim" para confirmar.'),
  ('configuracoes.toast.cat_criada', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Categoria criada'),
  ('configuracoes.toast.cat_excluida', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Categoria excluída'),
  ('configuracoes.toast.excluir_com_subs', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Não é possível excluir: existem subcategorias nessa categoria.'),
  ('configuracoes.toast.idioma_salvo', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Idioma salvo. Será aplicado quando as traduções estiverem disponíveis.'),
  ('configuracoes.toast.salvas', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Configurações salvas.'),
  ('configuracoes.toast.sub_atualizada', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Subcategoria atualizada'),
  ('configuracoes.toast.sub_com_historico', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Esta subcategoria tem histórico vinculado. Marque "Mover mesmo assim" para confirmar.'),
  ('configuracoes.toast.sub_criada', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Subcategoria criada'),
  ('configuracoes.toast.sub_excluida', 'configuracoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/configuracoes.js', 'Subcategoria excluída'),
  ('configuracoes.validacao.cat_nome_obrigatorio', 'configuracoes', 'ui', 'usuario', 'Auto-extraído de src/js/pages/configuracoes.js', 'Informe o nome da categoria'),
  ('configuracoes.validacao.cat_obrigatoria', 'configuracoes', 'ui', 'usuario', 'Auto-extraído de src/js/pages/configuracoes.js', 'Selecione uma categoria'),
  ('configuracoes.validacao.sub_nome_obrigatorio', 'configuracoes', 'ui', 'usuario', 'Auto-extraído de src/js/pages/configuracoes.js', 'Informe o nome da subcategoria'),
  ('contas.descricao', 'contas', 'ui', 'usuario', 'Auto-extraído de contas.html', 'Bancos, cartões, carteiras e investimentos. Alimenta as demais telas.'),
  ('contas.empty.mensagem', 'contas', 'ui', 'usuario', 'Auto-extraído de contas.html', 'Cadastre seu primeiro banco, cartão ou carteira pra começar a controlar suas finanças.'),
  ('contas.empty.titulo', 'contas', 'sistema', 'usuario', 'Auto-extraído de contas.html', 'Nenhuma conta cadastrada'),
  ('contas.titulo', 'contas', 'sistema', 'usuario', 'Auto-extraído de contas.html', 'Contas'),
  ('contas.toast.atualizada', 'contas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/contas.js', 'Conta atualizada'),
  ('contas.toast.criada', 'contas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/contas.js', 'Conta criada'),
  ('contas.toast.deletada', 'contas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/contas.js', 'Conta deletada permanentemente'),
  ('contas.toast.erro_carregar', 'contas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/contas.js', 'Erro ao carregar contas'),
  ('contas.validacao.desde_obrigatorio', 'contas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/contas.js', 'Informe a data inicial (Desde)'),
  ('contas.validacao.dia_fechamento', 'contas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/contas.js', 'Informe o dia de fechamento da fatura (1–31)'),
  ('contas.validacao.dia_vencimento', 'contas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/contas.js', 'Informe o dia de vencimento da fatura (1–31)'),
  ('contas.validacao.nome_obrigatorio', 'contas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/contas.js', 'Informe o nome do banco/cartão'),
  ('contatos.descricao', 'contatos', 'ui', 'usuario', 'Auto-extraído de contatos.html', 'Clientes e fornecedores. Histórico de reconhecimento automático por extrato bancário.'),
  ('contatos.titulo', 'contatos', 'sistema', 'usuario', 'Auto-extraído de contatos.html', 'Contatos'),
  ('contatos.toast.arquivado', 'contatos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/contatos.js', 'Contato arquivado.'),
  ('contatos.toast.reativado', 'contatos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/contatos.js', 'Contato reativado.'),
  ('dividas.btn_nova', 'dividas', 'ui', 'usuario', 'Auto-extraído de dividas.html', 'Nova dívida'),
  ('dividas.descricao', 'dividas', 'ui', 'usuario', 'Auto-extraído de dividas.html', 'Acompanhe dívidas ativas, em negociação e quitadas com barras de progresso.'),
  ('dividas.eyebrow', 'dividas', 'ui', 'usuario', 'Auto-extraído de dividas.html', 'Controle'),
  ('dividas.modal.label.credor', 'dividas', 'modal', 'usuario', 'Auto-extraído de dividas.html', 'Credor'),
  ('dividas.modal.label.nome', 'dividas', 'modal', 'usuario', 'Auto-extraído de dividas.html', 'Nome da dívida *'),
  ('dividas.modal.placeholder.credor', 'dividas', 'modal', 'usuario', 'Auto-extraído de dividas.html', 'Buscar contato ou digitar novo nome…'),
  ('dividas.modal.placeholder.nome', 'dividas', 'modal', 'usuario', 'Auto-extraído de dividas.html', 'Ex: Financiamento carro'),
  ('dividas.titulo', 'dividas', 'sistema', 'usuario', 'Auto-extraído de dividas.html', 'Dívidas'),
  ('dividas.toast.arquivada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Dívida arquivada (movida para Terminado)'),
  ('dividas.toast.atualizada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Dívida atualizada'),
  ('dividas.toast.categoria_nao_encontrada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Categoria "Dívidas" não encontrada — vá em Configurações para criá-la antes.'),
  ('dividas.toast.criada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Dívida cadastrada'),
  ('dividas.toast.erro_arquivar', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao arquivar'),
  ('dividas.toast.erro_carregar', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao carregar dívidas'),
  ('dividas.toast.erro_excluir', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao excluir'),
  ('dividas.toast.erro_restaurar', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao restaurar'),
  ('dividas.toast.erro_salvar', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Erro ao salvar'),
  ('dividas.toast.excluida', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Dívida excluída'),
  ('dividas.toast.taxa_atualizada', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Taxa atualizada'),
  ('dividas.toast.todas_parcelas_pagas', 'dividas', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/dividas.js', 'Todas as parcelas já foram pagas'),
  ('dividas.validacao.conta_debitada', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Selecione a conta debitada — pagamento sempre é registrado em Transações.'),
  ('dividas.validacao.data_inicio', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe a data de início'),
  ('dividas.validacao.data_pagamento', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe a data de pagamento'),
  ('dividas.validacao.desconto_excede', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Desconto não pode exceder o total de juros'),
  ('dividas.validacao.nome_obrigatorio', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe o nome da dívida'),
  ('dividas.validacao.nova_taxa', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe a nova taxa'),
  ('dividas.validacao.parcelas_obrigatorias', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe o número de parcelas'),
  ('dividas.validacao.regime_sem_parcelas', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Regime selecionado — informe o número de parcelas.'),
  ('dividas.validacao.valor_total', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe um valor total válido'),
  ('dividas.validacao.vigencia', 'dividas', 'ui', 'usuario', 'Auto-extraído de src/js/pages/dividas.js', 'Informe a data de vigência'),
  ('feedback.descricao', 'feedback', 'ui', 'usuario', 'Auto-extraído de feedback.html', 'Encontrou um bug, tem uma ideia, ou quer sugerir uma funcionalidade nova? Manda aqui — vou ler tudo.'),
  ('feedback.group.analise', 'feedback', 'ui', 'usuario', 'Auto-extraído de src/js/pages/feedback.js', 'Em análise e em andamento'),
  ('feedback.group.concluidas', 'feedback', 'ui', 'usuario', 'Auto-extraído de src/js/pages/feedback.js', 'Concluídas e rejeitadas'),
  ('feedback.group.novas', 'feedback', 'ui', 'usuario', 'Auto-extraído de src/js/pages/feedback.js', 'Novas'),
  ('feedback.placeholder.titulo', 'feedback', 'ui', 'usuario', 'Auto-extraído de feedback.html', 'Resumo curto do que aconteceu ou da ideia'),
  ('feedback.titulo', 'feedback', 'sistema', 'usuario', 'Auto-extraído de feedback.html', 'Sugestões & Bugs'),
  ('feedback.toast.enviado', 'feedback', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/feedback.js', 'Enviado! Obrigado pelo feedback.'),
  ('feedback.validacao.campos_obrigatorios', 'feedback', 'ui', 'usuario', 'Auto-extraído de src/js/pages/feedback.js', 'Preencha todos os campos.'),
  ('feedback_publico.btn.outra_entrada', 'feedback_publico', 'ui', 'usuario', 'Auto-extraído de feedback-publico.html', 'Enviar outra entrada'),
  ('feedback_publico.success.texto', 'feedback_publico', 'ui', 'usuario', 'Auto-extraído de feedback-publico.html', 'Valeu por mandar — vou ler com atenção.'),
  ('feedback_publico.success.titulo', 'feedback_publico', 'sistema', 'usuario', 'Auto-extraído de feedback-publico.html', 'Recebido!'),
  ('feedback_publico.validacao.campos', 'feedback_publico', 'ui', 'usuario', 'Auto-extraído de src/js/pages/feedback-publico.js', 'Preencha tipo, título e descrição.'),
  ('global.btn.cancelar', 'global', 'ui', 'usuario', 'Auto-extraído de investimentos.html', 'Cancelar'),
  ('global.btn.fechar', 'global', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Fechar'),
  ('global.btn.salvar', 'global', 'ui', 'usuario', 'Auto-extraído de investimentos.html', 'Salvar'),
  ('importar.descricao', 'importar', 'ui', 'usuario', 'Auto-extraído de importar.html', 'Importe CSV ou Excel do seu banco. As transações entram como'),
  ('importar.titulo', 'importar', 'sistema', 'usuario', 'Auto-extraído de importar.html', 'Importar transações'),
  ('importar.toast.arquivo_vazio', 'importar', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/importar.js', 'Arquivo vazio ou sem dados suficientes.'),
  ('importar.toast.carregando_sheetjs', 'importar', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/importar.js', 'Carregando SheetJS para ler Excel…'),
  ('importar.toast.formato_nao_suportado', 'importar', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/importar.js', 'Formato não suportado. Use CSV, XLSX ou XLS.'),
  ('importar.toast.parser_falhou', 'importar', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/importar.js', 'Não foi possível carregar o parser Excel. Verifique sua conexão.'),
  ('investimentos.btn.novo', 'investimentos', 'ui', 'usuario', 'Auto-extraído de investimentos.html', '+ Novo projeto'),
  ('investimentos.descricao', 'investimentos', 'ui', 'usuario', 'Auto-extraído de investimentos.html', 'Cada projeto é uma meta. Compromissos do grupo Investimentos podem ser atrelados a um projeto.'),
  ('investimentos.empty.btn', 'investimentos', 'ui', 'usuario', 'Auto-extraído de investimentos.html', '+ Criar primeiro projeto'),
  ('investimentos.empty.titulo', 'investimentos', 'sistema', 'usuario', 'Auto-extraído de investimentos.html', 'Nenhum projeto ainda'),
  ('investimentos.titulo', 'investimentos', 'sistema', 'usuario', 'Auto-extraído de investimentos.html', 'Investimentos'),
  ('investimentos.toast.atualizado', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Projeto atualizado'),
  ('investimentos.toast.criado', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Projeto criado'),
  ('investimentos.toast.criado_com_compromisso', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Projeto criado e compromisso vinculado'),
  ('investimentos.toast.erro_carregar', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Erro ao carregar projetos'),
  ('investimentos.toast.saldo_atualizado', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Saldo inicial atualizado'),
  ('investimentos.toast.schema_desatualizado', 'investimentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/investimentos.js', 'Schema desatualizado. Rode a migration 0016 + 0017 no Supabase.'),
  ('investimentos.validacao.aporte_obrigatorio', 'investimentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/investimentos.js', 'Informe o valor do aporte do compromisso'),
  ('investimentos.validacao.categoria_obrigatoria', 'investimentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/investimentos.js', 'Selecione uma categoria para o compromisso'),
  ('investimentos.validacao.data_aporte_obrigatoria', 'investimentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/investimentos.js', 'Informe a data do primeiro aporte'),
  ('investimentos.validacao.nome_obrigatorio', 'investimentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/investimentos.js', 'Informe o nome do projeto'),
  ('login.aviso.supabase_config', 'login', 'ui', 'usuario', 'Auto-extraído de src/js/pages/login.js', 'Configure Supabase em src/js/lib/config.js'),
  ('login.titulo_forgot', 'login', 'sistema', 'usuario', 'Auto-extraído de index.html', 'Recuperar senha'),
  ('login.titulo_login', 'login', 'sistema', 'usuario', 'Auto-extraído de index.html', 'Bem-vindo de volta'),
  ('login.titulo_signup', 'login', 'sistema', 'usuario', 'Auto-extraído de index.html', 'Criar sua conta'),
  ('login.toast.bem_vindo', 'login', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/login.js', 'Bem-vindo de volta!'),
  ('login.toast.conta_criada_confirmacao', 'login', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/login.js', 'Conta criada! Verifique seu email pra confirmar antes de entrar.'),
  ('login.toast.credenciais_invalidas', 'login', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/login.js', 'Email ou senha incorretos'),
  ('login.toast.email_existe', 'login', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/login.js', 'Este email já está cadastrado. Tente fazer login.'),
  ('login.toast.email_nao_confirmado', 'login', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/login.js', 'Confirme seu email antes de entrar (verifique sua caixa de entrada)'),
  ('login.toast.erro_email', 'login', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/login.js', 'Erro ao enviar email'),
  ('login.toast.erro_login', 'login', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/login.js', 'Erro ao fazer login'),
  ('login.toast.erro_signup', 'login', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/login.js', 'Erro ao criar conta'),
  ('login.toast.link_enviado', 'login', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/login.js', 'Link de recuperação enviado pro seu email.'),
  ('login.validacao.email_invalido', 'login', 'ui', 'usuario', 'Auto-extraído de src/js/pages/login.js', 'Informe um email válido'),
  ('login.validacao.nome_obrigatorio', 'login', 'ui', 'usuario', 'Auto-extraído de src/js/pages/login.js', 'Informe seu nome'),
  ('login.validacao.senha_minimo', 'login', 'ui', 'usuario', 'Auto-extraído de src/js/pages/login.js', 'Senha deve ter no mínimo 6 caracteres'),
  ('login.validacao.senha_obrigatoria', 'login', 'ui', 'usuario', 'Auto-extraído de src/js/pages/login.js', 'A senha precisa de no mínimo 6 caracteres'),
  ('minha.chave', 'minha', 'ui', 'usuario', 'Auto-extraído de src/js/lib/textos.js', 'Texto pt-BR'),
  ('nav.dividas', 'nav', 'ui', 'usuario', 'Auto-extraído de dividas.html', 'Dívidas'),
  ('novidades.descricao', 'novidades', 'ui', 'usuario', 'Auto-extraído de novidades.html', 'Registro de todas as melhorias, correções e novas funcionalidades publicadas no FinFlow.'),
  ('novidades.titulo', 'novidades', 'sistema', 'usuario', 'Auto-extraído de novidades.html', 'Novidades'),
  ('orcamento.descricao', 'orcamento', 'ui', 'usuario', 'Auto-extraído de orcamento.html', 'Visão financeira mensal — gerada automaticamente a partir dos seus compromissos. Edite valores específicos sem alterar a configuração base.'),
  ('orcamento.titulo', 'orcamento', 'sistema', 'usuario', 'Auto-extraído de orcamento.html', 'Orçamento Geral'),
  ('orcamento.toast.erro_gerar', 'orcamento', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/orcamento.js', 'Erro ao gerar orçamento'),
  ('orcamento.validacao.valor_invalido', 'orcamento', 'ui', 'usuario', 'Auto-extraído de src/js/pages/orcamento.js', 'Valor inválido'),
  ('pagamentos.btn.salvar_observacao', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Salvar observação'),
  ('pagamentos.descricao', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Controle do que foi pago no mês. Marque status e registre o valor real efetivamente pago.'),
  ('pagamentos.empty.btn', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Ir para Compromissos'),
  ('pagamentos.empty.mensagem', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de pagamentos.html', 'Cadastre compromissos ativos pra começar a registrar pagamentos. Pagamentos são gerados automaticamente a partir do orçamento.'),
  ('pagamentos.empty.titulo', 'pagamentos', 'sistema', 'usuario', 'Auto-extraído de pagamentos.html', 'Nenhum pagamento neste mês'),
  ('pagamentos.titulo', 'pagamentos', 'sistema', 'usuario', 'Auto-extraído de pagamentos.html', 'Pagamentos'),
  ('pagamentos.toast.erro_limpar', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Erro ao limpar pagamentos'),
  ('pagamentos.toast.erro_marcar_pago', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Erro ao marcar como pago'),
  ('pagamentos.toast.limpos', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Pagamentos pendentes limpos. Regenerando…'),
  ('pagamentos.toast.marcado_pago', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Marcado como pago'),
  ('pagamentos.toast.regenerados', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Blocos regenerados'),
  ('pagamentos.toast.schema_desatualizado', 'pagamentos', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/pagamentos.js', 'Schema desatualizado. Rode a migration 0011 no Supabase pra blocos dinâmicos.'),
  ('pagamentos.validacao.data_inicio', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/pagamentos.js', 'Informe a data de início'),
  ('pagamentos.validacao.valor_invalido', 'pagamentos', 'ui', 'usuario', 'Auto-extraído de src/js/pages/pagamentos.js', 'Valor inválido'),
  ('perfil.confirm.remover_foto', 'perfil', 'ui', 'usuario', 'Auto-extraído de src/js/pages/perfil.js', 'Remover a foto do seu perfil?'),
  ('perfil.descricao', 'perfil', 'ui', 'usuario', 'Auto-extraído de perfil.html', 'Foto, dados pessoais, redes sociais e plano de assinatura.'),
  ('perfil.hint.tipos_imagem', 'perfil', 'ui', 'usuario', 'Auto-extraído de perfil.html', 'JPG, PNG, WEBP ou GIF até 5 MB.'),
  ('perfil.titulo', 'perfil', 'sistema', 'usuario', 'Auto-extraído de perfil.html', 'Meu perfil'),
  ('perfil.toast.atualizado', 'perfil', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/perfil.js', 'Perfil atualizado'),
  ('perfil.toast.enviando_foto', 'perfil', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/perfil.js', 'Enviando foto…'),
  ('perfil.toast.erro_url_foto', 'perfil', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/perfil.js', 'Não foi possível gerar a URL pública da foto'),
  ('perfil.toast.foto_atualizada', 'perfil', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/perfil.js', 'Foto atualizada'),
  ('perfil.toast.foto_removida', 'perfil', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/perfil.js', 'Foto removida'),
  ('perfil.toast.sem_foto', 'perfil', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/perfil.js', 'Você não tem foto ainda'),
  ('perfil.validacao.arquivo_imagem', 'perfil', 'ui', 'usuario', 'Auto-extraído de src/js/pages/perfil.js', 'Arquivo precisa ser uma imagem'),
  ('perfil.validacao.imagem_tamanho', 'perfil', 'ui', 'usuario', 'Auto-extraído de src/js/pages/perfil.js', 'Imagem maior que 5 MB. Reduza antes de subir.'),
  ('relatorios.descricao', 'relatorios', 'ui', 'usuario', 'Auto-extraído de relatorios.html', 'Fluxo de caixa, previsto vs real, gastos por categoria. Exporte em CSV, Excel ou imprima em PDF.'),
  ('relatorios.titulo', 'relatorios', 'sistema', 'usuario', 'Auto-extraído de relatorios.html', 'Relatórios'),
  ('relatorios.toast.carregando_sheetjs', 'relatorios', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/relatorios.js', 'Carregando SheetJS…'),
  ('relatorios.toast.csv_exportado', 'relatorios', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/relatorios.js', 'CSV exportado'),
  ('relatorios.toast.sheetjs_falhou', 'relatorios', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/relatorios.js', 'Não foi possível carregar SheetJS para exportar XLSX'),
  ('relatorios.toast.xlsx_exportado', 'relatorios', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/relatorios.js', 'Excel (.xlsx) exportado'),
  ('relatorios.validacao.datas_obrigatorias', 'relatorios', 'ui', 'usuario', 'Auto-extraído de src/js/pages/relatorios.js', 'Informe as duas datas do período'),
  ('relatorios.validacao.datas_ordem', 'relatorios', 'ui', 'usuario', 'Auto-extraído de src/js/pages/relatorios.js', 'Data de início deve ser anterior ao fim'),
  ('transacoes.descricao', 'transacoes', 'ui', 'usuario', 'Auto-extraído de transacoes.html', 'Registro real do dinheiro que entrou e saiu — diferente do orçamento (planejado) e dos pagamentos (status mensal).'),
  ('transacoes.empty.btn', 'transacoes', 'ui', 'usuario', 'Auto-extraído de transacoes.html', '+ Nova transação'),
  ('transacoes.empty.mensagem', 'transacoes', 'ui', 'usuario', 'Auto-extraído de transacoes.html', 'Registre a primeira transação para começar seu diário financeiro.'),
  ('transacoes.empty.titulo', 'transacoes', 'sistema', 'usuario', 'Auto-extraído de transacoes.html', 'Nenhuma transação ainda'),
  ('transacoes.titulo', 'transacoes', 'sistema', 'usuario', 'Auto-extraído de transacoes.html', 'Transações'),
  ('transacoes.toast.erro_carregar', 'transacoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/transacoes.js', 'Erro ao carregar transações'),
  ('transacoes.toast.erro_cotacao', 'transacoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/transacoes.js', 'Não foi possível buscar a cotação.'),
  ('transacoes.toast.erro_excluir', 'transacoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/transacoes.js', 'Erro ao excluir'),
  ('transacoes.toast.reconciliada', 'transacoes', 'toast', 'notificacao', 'Auto-extraído de src/js/pages/transacoes.js', 'Transação reconciliada'),
  ('transacoes.validacao.conta_obrigatoria', 'transacoes', 'ui', 'usuario', 'Auto-extraído de src/js/pages/transacoes.js', 'Selecione uma conta'),
  ('transacoes.validacao.data_obrigatoria', 'transacoes', 'ui', 'usuario', 'Auto-extraído de src/js/pages/transacoes.js', 'Informe a data'),
  ('transacoes.validacao.datas_obrigatorias', 'transacoes', 'ui', 'usuario', 'Auto-extraído de src/js/pages/transacoes.js', 'Informe as duas datas do período'),
  ('transacoes.validacao.datas_ordem', 'transacoes', 'ui', 'usuario', 'Auto-extraído de src/js/pages/transacoes.js', 'Data de início deve ser anterior ao fim'),
  ('tutorial.cat.analise', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Análise'),
  ('tutorial.cat.cadastros', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Cadastros'),
  ('tutorial.cat.configuracao', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Configuração'),
  ('tutorial.cat.operacional', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Operacional'),
  ('tutorial.cat.visao-geral', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Visão Geral'),
  ('tutorial.compromissos.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Cadastros'),
  ('tutorial.compromissos.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O que são Compromissos?'),
  ('tutorial.compromissos.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Tipos de compromisso'),
  ('tutorial.compromissos.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Criando um compromisso'),
  ('tutorial.compromissos.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Valor variável'),
  ('tutorial.compromissos.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Indicador de limite comprometido'),
  ('tutorial.compromissos.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Duplicar um compromisso'),
  ('tutorial.compromissos.section.6.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Transferências'),
  ('tutorial.compromissos.section.7.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Compromissos se conecta com outras telas'),
  ('tutorial.compromissos.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O coração do planejamento: suas receitas e despesas recorrentes.'),
  ('tutorial.compromissos.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Configure seus compromissos com precisão — eles são o planejamento, e Pagamentos é a execução.'),
  ('tutorial.compromissos.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Use a <strong>Periodicidade "Único"</strong> para lançamentos pontuais que ainda não viraram transações.'),
  ('tutorial.compromissos.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Vincule compromissos de dívida a uma <strong>Dívida</strong> para ver o progresso de quitação automaticamente.'),
  ('tutorial.compromissos.tip.3', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O campo <strong>Apelido</strong> aparece no lugar do nome nas listagens — use para nomes mais curtos e claros.'),
  ('tutorial.compromissos.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Compromissos'),
  ('tutorial.configuracoes.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Configuração'),
  ('tutorial.configuracoes.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Por que acessar Configurações primeiro?'),
  ('tutorial.configuracoes.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Aba Categorias'),
  ('tutorial.configuracoes.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Vínculos de categorias'),
  ('tutorial.configuracoes.section.3.body', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'A aba Contatos em Configurações oferece o mesmo gerenciamento que a tela dedicada de Contatos — você pode criar, editar e gerenciar contatos sem sair das Configurações.'),
  ('tutorial.configuracoes.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Aba Contatos'),
  ('tutorial.configuracoes.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Aba Aparência'),
  ('tutorial.configuracoes.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Aba Moedas'),
  ('tutorial.configuracoes.section.6.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Configurações se conecta com outras telas'),
  ('tutorial.configuracoes.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Categorias, aparência, moedas — personalize o FinFlow para você.'),
  ('tutorial.configuracoes.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Configure as categorias <strong>antes</strong> de começar a lançar compromissos — reorganizar depois é trabalhoso.'),
  ('tutorial.configuracoes.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Use cores diferentes para categorias principais — elas aparecem nos gráficos de Relatórios e ficam mais fáceis de identificar.'),
  ('tutorial.configuracoes.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'A opção de tema <strong>"Automático"</strong> é a mais conveniente para quem usa o FinFlow em múltiplos dispositivos.'),
  ('tutorial.configuracoes.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Configurações'),
  ('tutorial.contas.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Cadastros'),
  ('tutorial.contas.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Por que começar pelas Contas?'),
  ('tutorial.contas.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Criando uma conta'),
  ('tutorial.contas.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Configurações exclusivas de Cartão de Crédito'),
  ('tutorial.contas.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Visualizações: cards e tabela'),
  ('tutorial.contas.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Detalhes e ações em uma conta'),
  ('tutorial.contas.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Contas se conecta com outras telas'),
  ('tutorial.contas.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Bancos, cartões e carteiras — a base de tudo no FinFlow.'),
  ('tutorial.contas.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Cadastre <strong>todas</strong> as suas contas antes de começar a usar o sistema — isso evita retrabalho.'),
  ('tutorial.contas.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Use apelidos descritivos: "Bradesco Salário", "C6 Viagens", "Caixa Fundo Emergência".'),
  ('tutorial.contas.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Ao encerrar uma conta bancária, use <strong>Arquivar</strong> em vez de deletar — isso preserva o histórico.'),
  ('tutorial.contas.tip.3', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O badge de comprometimento no card aparece automaticamente quando você cadastra o limite e tem compromissos ativos no cartão.'),
  ('tutorial.contas.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Contas'),
  ('tutorial.contatos.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Cadastros'),
  ('tutorial.contatos.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O que são Contatos?'),
  ('tutorial.contatos.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Layout em dois painéis'),
  ('tutorial.contatos.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Criando um contato'),
  ('tutorial.contatos.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Reconhecimento automático de extrato'),
  ('tutorial.contatos.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Histórico de transações'),
  ('tutorial.contatos.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Proteção contra exclusão'),
  ('tutorial.contatos.section.6.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Contatos se conecta com outras telas'),
  ('tutorial.contatos.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Clientes, fornecedores e o motor de reconhecimento automático de extrato.'),
  ('tutorial.contatos.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Preencha o <strong>Nome no extrato</strong> com o texto exato do seu banco — copie e cole do extrato para evitar erros.'),
  ('tutorial.contatos.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Cadastre fornecedores recorrentes antes de importar extratos para aproveitar o reconhecimento automático.'),
  ('tutorial.contatos.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Use o tipo <strong>"Ambos"</strong> para contatos que às vezes pagam e às vezes recebem.'),
  ('tutorial.contatos.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Contatos'),
  ('tutorial.dashboard.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Visão Geral'),
  ('tutorial.dashboard.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O que é o Dashboard?'),
  ('tutorial.dashboard.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'KPIs do mês'),
  ('tutorial.dashboard.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Widgets disponíveis'),
  ('tutorial.dashboard.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como personalizar o Dashboard'),
  ('tutorial.dashboard.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como o Dashboard se conecta com outras telas'),
  ('tutorial.dashboard.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Sua central de controle financeiro em tempo real.'),
  ('tutorial.dashboard.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Deixe os widgets que você mais usa no topo — os indicadores BCB e câmbio são ótimos para quem tem investimentos no exterior.'),
  ('tutorial.dashboard.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O saldo realizado só inclui o que foi <strong>pago/recebido</strong>. Para ver o planejado, acesse Pagamentos.'),
  ('tutorial.dashboard.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Use os atalhos rápidos como ponto de partida do seu dia financeiro.'),
  ('tutorial.dashboard.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Dashboard'),
  ('tutorial.dividas.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Cadastros'),
  ('tutorial.dividas.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O que é a tela de Dívidas?'),
  ('tutorial.dividas.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'KPIs de dívidas'),
  ('tutorial.dividas.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Criando uma dívida'),
  ('tutorial.dividas.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Registrando um pagamento'),
  ('tutorial.dividas.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Visualizações disponíveis'),
  ('tutorial.dividas.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Dívidas se conecta com outras telas'),
  ('tutorial.dividas.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Acompanhe o progresso de cada dívida em direção à quitação.'),
  ('tutorial.dividas.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Crie um <strong>Compromisso de despesa</strong> para cada parcela mensal e vincule-o à dívida correspondente — o progresso será atualizado automaticamente.'),
  ('tutorial.dividas.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Use o status <strong>"Negociando"</strong> para dívidas em processo de renegociação.'),
  ('tutorial.dividas.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'A visualização <strong>Gantt</strong> ajuda a planejar quitações quando você tem múltiplas dívidas simultâneas.'),
  ('tutorial.dividas.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Dívidas'),
  ('tutorial.importar.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Operacional'),
  ('tutorial.importar.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O que é a importação de extrato?'),
  ('tutorial.importar.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Etapa 1 — Arquivo e conta'),
  ('tutorial.importar.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Etapa 2 — Mapeamento de colunas'),
  ('tutorial.importar.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Etapa 3 — Revisão e importação'),
  ('tutorial.importar.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Reconhecimento automático na importação'),
  ('tutorial.importar.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Importar se conecta com outras telas'),
  ('tutorial.importar.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Importe seu extrato bancário e categorize em segundos.'),
  ('tutorial.importar.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'A maioria dos bancos brasileiros oferece exportação em CSV no aplicativo ou site — procure por "Exportar extrato" ou "Baixar histórico".'),
  ('tutorial.importar.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Importe por períodos curtos (1 mês) para facilitar a revisão antes de importar.'),
  ('tutorial.importar.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Após importar, vá para Transações e categorize os lançamentos sem subcategoria — isso melhora os relatórios.'),
  ('tutorial.importar.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Importar Extrato'),
  ('tutorial.investimentos.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Cadastros'),
  ('tutorial.investimentos.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O que são Projetos de Investimento?'),
  ('tutorial.investimentos.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'KPIs de investimentos'),
  ('tutorial.investimentos.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Criando um projeto'),
  ('tutorial.investimentos.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como o progresso é calculado'),
  ('tutorial.investimentos.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Visualizações disponíveis'),
  ('tutorial.investimentos.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Investimentos se conecta com outras telas'),
  ('tutorial.investimentos.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Defina seus projetos e acompanhe o progresso rumo às suas metas.'),
  ('tutorial.investimentos.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Crie um compromisso de aporte mensal para cada projeto e vincule-o ao projeto — o progresso atualiza sozinho ao marcar como pago.'),
  ('tutorial.investimentos.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Use o <strong>Saldo inicial</strong> para registrar o que você já tem investido antes de começar no FinFlow.'),
  ('tutorial.investimentos.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Projetos <strong>Concluídos</strong> ainda aparecem no histórico — você pode ver quanto levou para atingir a meta.'),
  ('tutorial.investimentos.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Investimentos'),
  ('tutorial.pagamentos.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Operacional'),
  ('tutorial.pagamentos.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O que é a tela de Pagamentos?'),
  ('tutorial.pagamentos.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Navegação por mês'),
  ('tutorial.pagamentos.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Blocos quinzenais'),
  ('tutorial.pagamentos.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Status de pagamento'),
  ('tutorial.pagamentos.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Registrar valor real pago'),
  ('tutorial.pagamentos.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Pagamento parcial'),
  ('tutorial.pagamentos.section.6.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Filtros de status'),
  ('tutorial.pagamentos.section.7.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Pagamentos se conecta com outras telas'),
  ('tutorial.pagamentos.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'A execução mensal do seu orçamento — marque, controle, acompanhe.'),
  ('tutorial.pagamentos.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Crie o hábito de abrir Pagamentos uma vez por semana e marcar o que foi executado.'),
  ('tutorial.pagamentos.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Use o filtro <strong>"Atrasados"</strong> para nunca deixar passar uma conta vencida.'),
  ('tutorial.pagamentos.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O campo <strong>Observação</strong> em cada entrada é útil para anotar número de protocolo, comprovante ou nota.'),
  ('tutorial.pagamentos.tip.3', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Navegue para meses futuros para ter uma prévia do que está programado.'),
  ('tutorial.pagamentos.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Pagamentos'),
  ('tutorial.relatorios.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Análise'),
  ('tutorial.relatorios.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O que você encontra em Relatórios?'),
  ('tutorial.relatorios.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Filtro de período'),
  ('tutorial.relatorios.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Relatório 1: Fluxo de Caixa'),
  ('tutorial.relatorios.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Relatório 2: Previsto vs. Real'),
  ('tutorial.relatorios.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Relatório 3: Categorias'),
  ('tutorial.relatorios.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Exportação'),
  ('tutorial.relatorios.section.6.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Relatórios se conecta com outras telas'),
  ('tutorial.relatorios.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Analise seu histórico financeiro com gráficos e exportações.'),
  ('tutorial.relatorios.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Use <strong>Previsto vs. Real</strong> mensalmente para ver se seu orçamento está sendo respeitado.'),
  ('tutorial.relatorios.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'O relatório <strong>Categorias</strong> com período "Ano" revela padrões anuais de gastos que não aparecem na visão mensal.'),
  ('tutorial.relatorios.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Exporte para <strong>Excel</strong> para fazer análises personalizadas fora do FinFlow.'),
  ('tutorial.relatorios.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Relatórios'),
  ('tutorial.transacoes.category_label', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Operacional'),
  ('tutorial.transacoes.section.0.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Transações vs. Pagamentos — qual a diferença?'),
  ('tutorial.transacoes.section.1.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'KPIs de período'),
  ('tutorial.transacoes.section.2.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Registrando uma transação'),
  ('tutorial.transacoes.section.3.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Filtros e busca'),
  ('tutorial.transacoes.section.4.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Reconciliação'),
  ('tutorial.transacoes.section.5.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Ações em lote'),
  ('tutorial.transacoes.section.6.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Como Transações se conecta com outras telas'),
  ('tutorial.transacoes.tagline', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Registre movimentações reais e mantenha seu extrato reconciliado.'),
  ('tutorial.transacoes.tip.0', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Vincule a Subcategoria sempre que possível — isso enriquece os relatórios de Previsto vs. Real.'),
  ('tutorial.transacoes.tip.1', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Para quem usa importação de extrato, o trabalho em Transações é principalmente revisar e categorizar os lançamentos importados.'),
  ('tutorial.transacoes.tip.2', 'tutorial', 'ui', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Reconcilie semanalmente para manter o controle em dia.'),
  ('tutorial.transacoes.title', 'tutorial', 'sistema', 'usuario', 'Auto-extraído de src/js/lib/tutorial-content.js', 'Transações')
on conflict (chave) do update
  set pt_br      = excluded.pt_br,
      pagina     = excluded.pagina,
      categoria  = excluded.categoria,
      updated_at = now();
