// =============================================================
// FinFlow — Registro de versões
// Adicione entradas novas no INÍCIO do array.
// id deve ser único — é usado para rastrear o que o usuário já leu.
// type: 'new' | 'fix' | 'improvement'
// =============================================================

export const CHANGELOG = [
  {
    id: '2026-05-18-delete-cascade-e-picker',
    version: '0.7.2',
    date: '18/05/2026',
    title: 'Compromissos — correções de exclusão em cascata e picker de investimento',
    items: [
      { type: 'fix', text: 'Botão "Editar" voltou a aparecer em compromissos de Custo de Vida, Receitas e demais categorias — ficava escondido indevidamente quando a subcategoria tinha um projeto vinculado como custo.' },
      { type: 'fix', text: 'Excluir uma subcategoria ou compromisso agora também exclui (ou arquiva) o financiamento/dívida ou projeto de investimento vinculado. Sem histórico → exclusão permanente; com histórico → arquivamento com opção de restauração.' },
      { type: 'fix', text: 'Picker "Vincular a investimento" mostrava lista vazia porque o campo status não era carregado na query de projetos.' },
      { type: 'improvement', text: 'Picker "Vincular a investimento" saiu de Configurações e foi para Compromissos (ao editar um compromisso de Custo de Vida) e para Investimentos (modal de edição do projeto).' },
      { type: 'new', text: 'Modal de edição de projeto em Investimentos: nova seção "Custos vinculados" lista subcategorias do Custo de Vida vinculadas, com opção de desvincular ou adicionar novas.' },
    ],
  },
  {
    id: '2026-05-18-custos-vinculados',
    version: '0.7.1',
    date: '18/05/2026',
    title: 'Custos vinculados — várias subs do Custo de Vida no mesmo projeto/dívida',
    items: [
      { type: 'new', text: 'Subcategorias do bloco "Custo de Vida" agora podem ser vinculadas a um projeto de investimento ou financiamento existente. Ex: assinaturas GitHub, conta celular e anúncios vinculados ao mesmo projeto "Side Project SaaS".' },
      { type: 'new', text: 'Modal de subcategoria (em Configurações): novo select "Vincular a projeto ou dívida" — só visível quando a categoria-pai é do bloco Custo de Vida. Dropdown agrupado com Projetos de Investimento e Financiamentos ativos.' },
      { type: 'new', text: 'Card do projeto em Investimentos: nova seção "Custos vinculados" listando as subs + total mensal previsto.' },
      { type: 'new', text: 'Card do financiamento em Financiamentos e Dívidas: mesma seção "Custos vinculados" (ex: IPVA e seguro do carro vinculados ao financiamento do veículo).' },
      { type: 'fix', text: 'Removida categoria órfã "Obejtivos" (typo de "Objetivos") da conta de admin que sobrou da limpeza anterior. Não estava nos seeds — não afetava novos usuários.' },
    ],
  },
  {
    id: '2026-05-18-patrimonio-fipe',
    version: '0.7.0',
    date: '18/05/2026',
    title: 'Patrimônio — cálculo com ativos físicos e investimentos',
    items: [
      { type: 'new', text: 'Novo conceito: marque "Incluir no cálculo de patrimônio" no modal de qualquer financiamento ou projeto de investimento para somá-lo ao seu patrimônio total.' },
      { type: 'new', text: 'Ativo subjacente em financiamentos: vincule um veículo (busca FIPE em tempo real) ou um imóvel (valor manual) ao financiamento. Patrimônio do ativo = valor atual − saldo devedor.' },
      { type: 'new', text: 'Wizard FIPE: 3 selects encadeados (marca → modelo → ano) que buscam direto da API parallelum.com.br. Valor FIPE oficial exibido após seleção do ano, com mês de referência.' },
      { type: 'new', text: 'Cache de 24h da API FIPE no localStorage — segunda consulta é instantânea.' },
      { type: 'new', text: 'Novo widget no Dashboard: "Patrimônio (ativos)" com total + breakdown por item (ativos físicos e investimentos).' },
      { type: 'new', text: 'Tag visual "💎 Patrimônio" nos cards de financiamentos e projetos selecionados.' },
      { type: 'improvement', text: 'Migration 0102 cria tabela ativos_subjacentes (1:1 com dívida via FK unique) + colunas inclui_no_patrimonio em dividas e projetos_investimento.' },
      { type: 'fix', text: 'Patrimônio corrente (incluindo saldos de contas) virá em iteração futura — exibido como hint no widget.' },
    ],
  },
  {
    id: '2026-05-17-fix-autocriacao-divida',
    version: '0.6.5',
    date: '17/05/2026',
    title: 'Dívidas — correção de auto-criação + limpeza de duplicatas',
    items: [
      { type: 'fix', text: 'Correção: ao criar uma nova dívida, o compromisso placeholder não era gerado quando a categoria "Dívidas" tinha um nome ligeiramente diferente. Agora busca por grupo em vez de nome.' },
      { type: 'fix', text: 'Migration 0098: zera "31.344 - DAS" (sem configuração) e remove dívidas duplicadas por nome, mantendo a versão com maior valor configurado.' },
    ],
  },
  {
    id: '2026-05-17-grupos-minimizaveis',
    version: '0.6.4',
    date: '17/05/2026',
    title: 'Dívidas e Investimentos — grupos minimizáveis + reset de dados',
    items: [
      { type: 'new', text: 'Grupos de Dívidas e Investimentos agora podem ser minimizados: clique no cabeçalho do grupo para recolher ou expandir. Estado salvo no localStorage.' },
      { type: 'fix', text: 'Reset completo de dívidas e projetos de investimento corrigido: a migration anterior falhava silenciosamente por FK em transacoes.divida_id. Agora desvincula transações antes de deletar.' },
    ],
  },
  {
    id: '2026-05-17-dividas-investimentos-autolink',
    version: '0.6.3',
    date: '17/05/2026',
    title: 'Dívidas e Investimentos — auto-vinculação bidirecional',
    items: [
      { type: 'new', text: 'Grupo "Sem Configuração" em Dívidas e Investimentos: dívidas sem valor total e projetos sem meta ficam neste grupo até o usuário configurar.' },
      { type: 'new', text: 'Auto-vinculação bidirecional: criar uma dívida ou projeto de investimento gera automaticamente um compromisso placeholder vinculado; criar um compromisso em categoria Dívidas/Investimentos com opção "Nova" gera automaticamente a dívida ou projeto correspondente.' },
      { type: 'improvement', text: 'Botão "Ir para Dívida" / "Ir para Projeto" sempre visível em compromissos de categorias Dívidas e Investimentos — substitui os botões Editar, Arquivar e Encerrar.' },
      { type: 'improvement', text: '"Por Começar" agora requer valor configurado (valor_total > 0 em Dívidas, meta_valor > 0 em Investimentos).' },
      { type: 'fix', text: 'Prevenção de nomes duplicados ao criar dívidas e projetos de investimento — exibe aviso ao usuário.' },
    ],
  },
  {
    id: '2026-05-17-remove-objetivos',
    version: '0.6.2',
    date: '17/05/2026',
    title: 'Categorias — remoção de Objetivos e proteção seletiva',
    items: [
      { type: 'fix', text: 'Categoria "Objetivos" removida do sistema: não é mais criada para novos usuários e foi excluída (junto com suas subcategorias: Casa nova, Aniversário dos filhos, Presentes de natal) de todos os usuários existentes.' },
      { type: 'improvement', text: 'Apenas Receita, Dívidas e Investimentos continuam como categorias protegidas (is_default=true, sem botões Editar/Deletar). Casa, Doações e Presentes e Educação e Saúde passaram a is_default=false — o usuário pode editá-las e deletá-las normalmente.' },
      { type: 'fix', text: 'Compromisso editado com mudança de tipo para Caixinha agora exibe o popup "Este compromisso foi convertido em caixinha."' },
    ],
  },
  {
    id: '2026-05-17-caixinha-detalhes-transacoes',
    version: '0.6.1',
    date: '17/05/2026',
    title: 'Caixinha — detalhes, histórico e badge em Transações',
    items: [
      { type: 'new', text: 'Card de Caixinha na página Contas é clicável e abre modal de detalhes com saldo atual, número de contribuições, histórico de transferências e opções Editar / Arquivar.' },
      { type: 'new', text: 'Página de Transações: transferências vinculadas a uma Caixinha exibem badge âmbar "Caixinha" + nome da caixinha (saída/entrada) na coluna de categoria.' },
      { type: 'new', text: 'Filtro de conta em Transações ganhou grupo "Caixinha" com ícone piggy bank — permite filtrar todas as movimentações de uma caixinha específica.' },
      { type: 'improvement', text: 'Grupo do conta-picker renomeado de "Caixinha" para "Reserva" (alinhado com o tipo de conta Cofrinho). Avatar no filtro usa círculo proporcional igual às contas bancárias.' },
      { type: 'fix', text: 'Filtro "Todas as contas" não exibe mais o círculo cinza "?" — avatar fica oculto quando nenhuma conta está selecionada.' },
      { type: 'fix', text: 'Modal de compromisso: sub-row sempre abre em modo visualização (detalhes + Arquivar / Atualizar / Editar). Botão Duplicar removido.' },
      { type: 'fix', text: 'Formulário de Caixinha: campo Banco/Cartão passou a ser obrigatório; mensagem de criação diz "caixinha criada" (antes dizia "subcategoria").' },
    ],
  },
  {
    id: '2026-05-17-dividas-a-receber',
    version: '0.6.0',
    date: '17/05/2026',
    title: 'Dívidas — suporte a "a pagar" e "a receber" (empréstimos)',
    items: [
      { type: 'new', text: 'Nova coluna `tipo` na tabela `dividas` (a_pagar | a_receber) — permite cadastrar tanto dívidas suas quanto empréstimos que outras pessoas devem a você.' },
      { type: 'new', text: 'Modal de dívida: toggle no topo "Eu devo (a pagar)" vs "Me devem (a receber)". Labels e placeholders trocam dinamicamente (Credor ↔ Devedor).' },
      { type: 'new', text: 'Cards de dívida a_receber ganham badge verde "↙ A receber" + borda esquerda verde para diferenciação visual.' },
      { type: 'new', text: 'KPIs do topo passam a refletir apenas dívidas a_pagar. Empréstimos a_receber ganham um card-resumo separado abaixo, em verde, com total e quanto já foi recebido.' },
      { type: 'improvement', text: 'Compromisso vinculado automático: dívidas a_receber geram compromisso do tipo `Receita` (entra como entrada no orçamento), enquanto a_pagar continuam gerando `Despesa`.' },
      { type: 'improvement', text: 'Modal de pagamento: título e botão viram "Recebimento" / "Registrar recebimento" quando a dívida é a_receber.' },
    ],
  },
  {
    id: '2026-05-17-fases-fixes-pos-v0-5-4',
    version: '0.5.5',
    date: '17/05/2026',
    title: 'Tracker de tickets com fases + fixes pós v0.5.4',
    items: [
      { type: 'new', text: 'Página de Desenvolvimento ganha coluna "Fase" (A..I) com badges coloridas, filtro por fase no topo e ordenação automática por fase. Cada ticket pode ter fase setada via dropdown clicável direto na linha — mesma UX de módulo/status.' },
      { type: 'new', text: 'Modal de detalhe do ticket: status e fase migrados para o header como chips de classificação, deixando o corpo do modal só com conteúdo descritivo.' },
      { type: 'fix', text: 'Aba "Configurações" do Orçamento ficava vazia após v0.5.4 — initColVisibility tentava ler .toolbar (renomeado para .orc-filter-bar) e quebrava todo o init.' },
      { type: 'improvement', text: 'Aba "Configurações" agrupa categorias em 3 seções coloridas (Contribuição / Sonhos / Custo de Vida) — mesmo layout da página de Configurações de Categorias.' },
      { type: 'fix', text: 'Página de Categorias: coluna "Vínculos" não permite mais criar compromisso. Mostra apenas vínculos existentes (badges); placeholder "—" quando não há.' },
      { type: 'fix', text: 'Página de Categorias: prompt "Criar compromisso" após salvar nova categoria/subcategoria foi removido. Modal fecha direto.' },
      { type: 'fix', text: 'Contato picker: mostra logo/foto quando disponível (campo logo_url agora é puxado no SELECT em Compromissos, Dívidas e Investimentos).' },
      { type: 'fix', text: 'Página de Categorias: criar/reordenar não joga mais o scroll pro topo. reloadAll preserva window.scrollY entre re-renders.' },
    ],
  },
  {
    id: '2026-05-16-orcamento-filtros-layout',
    version: '0.5.4',
    date: '16/05/2026',
    title: 'Orçamento — layout dos filtros mais compacto',
    items: [
      { type: 'improvement', text: 'Filtros da aba Configurações reorganizados em barra horizontal única: busca, Exibição, Status e view-toggle alinhados. Filtro por Categoria fica em linha separada com chips coloridas — economiza espaço vertical sem perder funcionalidades.' },
      { type: 'improvement', text: 'Nova classe utilitária `cf-status-tabs--compact` (padding e font-size menores) para filtros densos.' },
      { type: 'improvement', text: 'Layout responsivo: em telas estreitas o filtro vira coluna preservando todos os controles.' },
    ],
  },
  {
    id: '2026-05-16-orcamento-indicador-cabe',
    version: '0.5.3',
    date: '16/05/2026',
    title: 'Orçamento — somatórias e indicador "Cabe no orçamento?"',
    items: [
      { type: 'new', text: 'Aba Configurações: sumário no topo com Receitas mensais / Despesas mensais / Saldo + indicador colorido (verde = folga ≥20%, amarelo = passa apertado, vermelho = não cabe).' },
      { type: 'new', text: 'Breakdown por super-bloco (Contribuição, Sonhos, Custo de vida) com somatórias mensais — visual rápido de para onde está indo o dinheiro.' },
      { type: 'improvement', text: 'Cálculo mensal considera o período do compromisso: Mensal ×1, Quinzenal ×2, Semanal ×4.33, Anual ÷12, Único ignorado.' },
    ],
  },
  {
    id: '2026-05-16-orcamento-meses-passados',
    version: '0.5.2',
    date: '16/05/2026',
    title: 'Orçamento — aba "Meses passados" funcional',
    items: [
      { type: 'new', text: 'Aba "Meses passados": seletor de mês listando apenas meses dos últimos 12 que têm pagamentos lançados.' },
      { type: 'new', text: 'Tabela do mês selecionado mostra cada compromisso com status (Pago/Cartão/Cancelado/Parcial), valor previsto e valor realizado, agrupados por categoria.' },
      { type: 'new', text: 'Cartões de totalização ao final: total previsto, total realizado e diferença (verde se realizado ≤ previsto, vermelho caso contrário).' },
      { type: 'improvement', text: 'Apenas visualização — nenhuma edição possível, conforme o modelo de fontes de verdade introduzido no v0.4.0.' },
    ],
  },
  {
    id: '2026-05-16-orcamento-readonly-mensal-12meses',
    version: '0.5.1',
    date: '16/05/2026',
    title: 'Orçamento — abas Mensal e 12 meses são apenas visualização',
    items: [
      { type: 'improvement', text: 'Coluna "valor planejado" nas abas Mensal e 12 meses fica em modo somente leitura — edições só pela aba Configurações (ou pelas páginas de Dívidas/Projetos quando o compromisso é vinculado).' },
      { type: 'improvement', text: 'Colunas, badges, tags e gráficos das abas de visualização permanecem inalterados; apenas inputs de edição são bloqueados.' },
      { type: 'fix', text: 'saveCell agora ignora inputs com readonly/disabled — evita gravações acidentais a partir das abas de visualização.' },
    ],
  },
  {
    id: '2026-05-16-orcamento-unificado-tabs',
    version: '0.5.0',
    date: '16/05/2026',
    title: 'Orçamento unificado — Compromissos vira aba de Configurações',
    items: [
      { type: 'new', text: 'Página unificada "Orçamento" com 4 abas: Configurações, Mensal, 12 meses e Meses passados (placeholder).' },
      { type: 'improvement', text: 'A entrada "Compromissos" foi removida do menu lateral — agora vive como aba Configurações dentro de Orçamento.' },
      { type: 'improvement', text: 'Página atual de Compromissos passa a exibir título "Orçamento" e a tab strip ativa em Configurações.' },
      { type: 'improvement', text: 'Página atual de Orçamento exibe a mesma tab strip; URLs `/orcamento.html?tab=mensal|12meses|passados` selecionam a aba; `/orcamento.html?tab=configuracoes` redireciona para a página de Compromissos.' },
    ],
  },
  {
    id: '2026-05-16-criar-compromisso-divida-projeto',
    version: '0.4.1',
    date: '16/05/2026',
    title: 'Dívidas e Projetos — criação coerente do compromisso vinculado',
    items: [
      { type: 'new', text: 'Cards de Dívida sem compromisso vinculado exibem badge "⚠ Configurar compromisso" — clicar abre o modal pra preencher regime + parcelas e gera o compromisso automaticamente.' },
      { type: 'new', text: 'Cards de Projeto de Investimento sem compromisso vinculado exibem o mesmo badge — clicar abre o modal de edição já com a seção "Criar compromisso vinculado" aberta.' },
      { type: 'improvement', text: 'Dívidas: ao salvar com regime + parcelas, o compromisso vinculado agora é criado/atualizado com `valor_variavel=true` quando as parcelas variam (SAC, Customizado) e fica com `valor_base` fixo quando todas são iguais (Price).' },
      { type: 'improvement', text: 'Dívidas: o `orcamento_geral` do compromisso é regenerado mês a mês com o valor exato de cada parcela, calculado por `gerarTabela`. A janela `iniciado_em / terminado_em` fica alinhada com a primeira e a última parcela.' },
      { type: 'improvement', text: 'Dívidas: a função `ensureSubcategoriaForDivida` é idempotente — pode ser chamada a cada save sem duplicar registros (atualiza o existente).' },
      { type: 'improvement', text: 'Projetos: ao editar um projeto sem compromisso vinculado, a seção "Criar compromisso vinculado" aparece pré-marcada com a data alvo do projeto como sugestão de data inicial.' },
    ],
  },
  {
    id: '2026-05-16-compromissos-divida-projeto-fonte-verdade',
    version: '0.4.0',
    date: '16/05/2026',
    title: 'Refatoração — Dívidas e Projetos são fonte de verdade dos seus compromissos',
    items: [
      { type: 'improvement', text: 'Compromissos vinculados a Dívidas ou Projetos de Investimento agora só podem ser criados/editados pela página específica (Dívidas ou Investimentos). A página de Compromissos mostra os vínculos em modo leitura.' },
      { type: 'new', text: 'Modal de detalhes do compromisso: para itens vinculados a Dívida/Projeto, os botões Editar / Duplicar / Atualizar valor / Arquivar / Encerrar são substituídos por "Ir para Dívida" ou "Ir para Projeto".' },
      { type: 'new', text: 'Modal de novo compromisso: ao selecionar uma categoria de Dívida ou Investimento, o formulário esconde os campos e exibe um banner explicativo com botão direto para a página correta.' },
      { type: 'fix', text: 'Removida coluna `configurada` da tabela `dividas` e todo o fluxo "⚠ Configurar" do v0.3.9 — substituídos pela nova arquitetura.' },
      { type: 'improvement', text: 'Migração 0088 purga compromissos vinculados a dívidas/projetos existentes para garantir consistência com o novo modelo (a recriação será feita pela página específica em uma próxima versão).' },
    ],
  },
  {
    id: '2026-05-16-dividas-pendente-config',
    version: '0.3.9',
    date: '16/05/2026',
    title: 'Dívidas — indicador de configuração pendente',
    items: [
      { type: 'new', text: 'Dívidas sem configuração (regime não definido) exibem badge amarelo "⚠ Configurar" no card e na tabela — clique direto abre o modal para configurar' },
      { type: 'new', text: 'Modal da dívida: banner de aviso quando a dívida ainda não foi configurada + campos pré-preenchidos automaticamente a partir dos compromissos vinculados (valor, data de início, conta, credor)' },
      { type: 'new', text: 'Botão "Confirmar configuração" no modal: marca a dívida como configurada de forma explícita, sem alterar os demais campos' },
      { type: 'new', text: 'Página de Compromissos: chip "⚠ Configurar" ao lado do nome da dívida em linhas vinculadas a dívidas não configuradas' },
      { type: 'improvement', text: 'Migration retroativa: dívidas existentes com regime definido são automaticamente marcadas como configuradas' },
    ],
  },
  {
    id: '2026-05-16-kpi-cambio-real',
    version: '0.3.8',
    date: '16/05/2026',
    title: 'KPIs com câmbio do dia — Dívidas e Investimentos',
    items: [
      { type: 'improvement', text: 'Dívidas — "Total em aberto": valor principal agora é a soma de todas as dívidas convertidas para R$ usando o câmbio do dia (Frankfurter API); abaixo aparecem os valores originais por moeda (R$, USD, EUR, GBP…)' },
      { type: 'improvement', text: 'Dívidas — "Total pago": exibe apenas o total pago em R$ (moeda principal), sem linhas adicionais de outras moedas' },
      { type: 'improvement', text: 'Investimentos — "Total investido": valor principal convertido para R$ usando câmbio do dia; breakdown por moeda nas linhas abaixo quando há projetos em múltiplas moedas' },
      { type: 'improvement', text: 'Investimentos — "Projetos com meta": realizado e meta também convertidos para R$ para comparação consistente' },
    ],
  },
  {
    id: '2026-05-16-dividas-multimoeda-kpi',
    version: '0.3.7',
    date: '16/05/2026',
    title: 'Dívidas — suporte a moeda estrangeira nos KPIs',
    items: [
      { type: 'new', text: 'Formulário de dívida: novo campo "Moeda" para configurar dívidas em BRL, USD, EUR ou GBP — valores exibidos na moeda correta em cards, tabelas e histórico' },
      { type: 'fix', text: 'KPI "Total em aberto" e "Total pago": deixam de somar valores de moedas diferentes — BRL é exibido como valor principal; dívidas em moeda estrangeira aparecem como linha separada abaixo' },
    ],
  },
  {
    id: '2026-05-16-dividas-tabelas-pdf',
    version: '0.3.6',
    date: '16/05/2026',
    title: 'Dívidas — taxa efetiva nas tabelas, layout consistente e exportar PDF',
    items: [
      { type: 'new',         text: 'Tabela de amortização e histórico de pagamentos: nova coluna "Taxa (% a.m.)" mostrando a taxa real de cada parcela paga (juros ÷ saldo inicial), e a taxa estimada vigente para parcelas futuras' },
      { type: 'new',         text: 'Tabela de amortização: nova coluna "Pago em" mostrando a data real de pagamento nas parcelas já quitadas' },
      { type: 'new',         text: 'Exportar PDF: botão em ambos os modais (tabela de amortização e histórico) gera PDF completo com cabeçalho, resumo e tabela formatada' },
      { type: 'improvement', text: 'Tabela de amortização: resumo reformulado — exibe saldo devedor atual, próxima parcela, taxa vigente e totais projetados' },
      { type: 'improvement', text: 'Cards de dívida: meta-informações reorganizadas em duas linhas fixas (linha 1: datas e taxa; linha 2: regime, parcelas e conta) — visual idêntico em todos os cards' },
      { type: 'improvement', text: 'KPI widgets: "Total em aberto" e "Total pago" agora com o mesmo estilo de fonte e peso' },
      { type: 'improvement', text: 'Aba "Taxas" removida do histórico de dívidas — a taxa já é exibida por linha na tabela de pagamentos' },
    ],
  },
  {
    id: '2026-05-16-dividas-form-simplificado',
    version: '0.3.5',
    date: '16/05/2026',
    title: 'Dívidas — formulário simplificado + última parcela automática + simulador',
    items: [
      { type: 'new',         text: 'Formulário de dívida em modo Básico/Avançado — modo básico esconde campos técnicos e apresenta linguagem do dia a dia ("Parcelas iguais", "Parcelas que diminuem", "A dívida tem juros?")' },
      { type: 'new',         text: 'Última parcela automática (Customizado): ative "Calcular última parcela pelo saldo devedor" e o sistema quita o saldo residual + juros do mês — recalcula automaticamente conforme a taxa muda e pagamentos são feitos' },
      { type: 'new',         text: 'Simulador de antecipação: ao pagar múltiplas parcelas de uma vez, o modal de pagamento mostra a estimativa da nova última parcela após a antecipação' },
      { type: 'improvement', text: 'Histórico de dívidas: colunas separadas por tipo (amortização, juros em vermelho, desconto em verde), ordem cronológica (mais antiga primeiro) e resumo no topo' },
      { type: 'improvement', text: 'Tabela de amortização: nova coluna Desconto mostrando desconto real obtido em cada parcela paga; resumo ganha "Desconto obtido" quando houver' },
    ],
  },
  {
    id: '2026-05-16-dividas-historico-layout',
    version: '0.3.4',
    date: '16/05/2026',
    title: 'Dívidas — card de histórico de pagamentos reformulado',
    items: [
      { type: 'fix', text: 'Histórico de dívidas: textos de data, nome e breakdown de amortização/juros não se sobrepõem mais — cada informação ocupa sua própria linha' },
      { type: 'improvement', text: 'Modal de histórico ampliado para melhor leitura dos detalhes de cada pagamento' },
    ],
  },
  {
    id: '2026-05-16-categorias-modal-perf',
    version: '0.3.3',
    date: '16/05/2026',
    title: 'Categorias — modal de compromisso instantâneo + ajustes visuais',
    items: [
      { type: 'fix',         text: 'Modal de compromisso na página Categorias: aparecia tela cinza sem conteúdo — corrigido em 3 camadas (visibilidade, parâmetro embedded e timing do postMessage)' },
      { type: 'improvement', text: 'Modal de compromisso na página Categorias: abertura agora é instantânea — iframe pré-carregado em background com queries paralelas ao abrir a página' },
      { type: 'improvement', text: 'Tabela de Categorias: colunas Categoria, Subcategoria e Vínculos com mesma largura; Transações reduzida ao mínimo necessário e centralizada; espaçamento lateral equilibrado' },
    ],
  },
  {
    id: '2026-05-16-categorias-contatos-fixes',
    version: '0.3.2',
    date: '16/05/2026',
    title: 'Correções — Categorias, Contatos e Foto de perfil',
    items: [
      { type: 'fix',         text: 'Picker de contato: dropdown fecha corretamente antes de abrir o modal de criação' },
      { type: 'fix',         text: 'Crop de foto de perfil: botões de zoom não distorciam imagem antes do carregamento completo' },
      { type: 'fix',         text: 'Crop de foto de perfil: recorte salvo corresponde exatamente à área visível no viewport circular' },
      { type: 'fix',         text: 'Popup de compromisso na página Categorias: abertura sem flash visual' },
      { type: 'improvement', text: 'Categorias: coluna Vínculos mais larga — badges de compromisso, dívida e projeto ficam todos na mesma linha' },
      { type: 'improvement', text: 'Vínculos exibidos na ordem: Compromisso → Dívida → Projeto de investimento (em Categorias e no card de Contatos)' },
    ],
  },
  {
    id: '2026-05-15-contatos-foto-crop',
    version: '0.3.1',
    date: '15/05/2026',
    title: 'Foto de perfil com crop + Vínculos completos',
    items: [
      { type: 'new',         text: 'Crop interativo ao adicionar foto de perfil — arraste para reposicionar e use zoom in/out antes de salvar' },
      { type: 'improvement', text: 'Badges F (Fornecedor) / C (Cliente) / U (Usuário) agora sempre visíveis na lista de contatos, mesmo quando o contato tem foto' },
      { type: 'new',         text: 'Aba Vínculos nos detalhes de contato agora exibe também Compromissos vinculados' },
      { type: 'new',         text: 'Hover card em cada vínculo — passe o mouse sobre dívidas, projetos ou compromissos para ver os detalhes sem sair da tela' },
    ],
  },
  {
    id: '2026-05-14-gerenciador-refinamentos',
    version: '0.3.0',
    date: '14/05/2026',
    title: 'Gerenciador de Sugestões — refinamentos e paridade visual',
    items: [
      { type: 'improvement', text: 'Widgets de stats idênticos nas páginas Gerenciador e Sugestões & Bugs — 6 cards na mesma ordem: Total, Pendente, Aprovadas, Em Progresso, Concluídas, Rejeitadas' },
      { type: 'improvement', text: 'Cor do widget e badge "Aprovadas" alterada de roxo para azul em toda a interface' },
      { type: 'new',         text: 'Campo "Retorno para o usuário" no modal de edição do Gerenciador — mensagem visível pelo usuário na página Sugestões & Bugs' },
      { type: 'fix',         text: 'Dropdown de status no Gerenciador corrigido — agora abre e fecha corretamente ao clicar' },
      { type: 'new',         text: 'Tab "Todas" no Gerenciador para visualizar entradas de todos os status de uma vez' },
      { type: 'new',         text: 'Destaque "Minha sugestão" na página Novidades — sugestões aprovadas do próprio usuário aparecem com fundo roxo e badge identificador' },
    ],
  },
  {
    id: '2026-05-14-gerenciador-sugestoes',
    version: '0.2.9',
    date: '14/05/2026',
    title: 'Gerenciador de Sugestões + Novidades redesenhada',
    items: [
      { type: 'new',         text: 'Gerenciador de Sugestões — painel admin completo para rastrear, priorizar e evoluir o status do feedback dos usuários' },
      { type: 'new',         text: 'Status "Aprovada" no fluxo de desenvolvimento — sinaliza sugestões aprovadas antes de entrar em progresso' },
      { type: 'new',         text: 'Página Novidades redesenhada: "Em desenvolvimento" ao lado das últimas 3 atualizações (com scroll interno) e histórico em 2 colunas' },
      { type: 'improvement', text: 'Painel de detalhes de contato exibe tipo correto "Usuário" para o perfil do próprio usuário' },
      { type: 'improvement', text: 'Navegação reorganizada — Feedback pelo avatar; Gerenciador de Sugestões integrado ao painel Admin' },
    ],
  },
  {
    id: '2026-05-13-endereco-estruturado',
    version: '0.2.8',
    date: '13/05/2026',
    title: 'Contatos e Perfil — endereço estruturado com busca por CEP',
    items: [
      { type: 'new',         text: 'Campo de endereço separado em CEP, logradouro, número, complemento, bairro, cidade e estado' },
      { type: 'new',         text: 'Busca automática de endereço pelo CEP via ViaCEP — preenche todos os campos de uma vez' },
      { type: 'improvement', text: 'Endereço disponível também no Perfil (sincronizado com o contato do usuário)' },
    ],
  },
  {
    id: '2026-05-13-phone-picker-iframe',
    version: '0.2.7',
    date: '13/05/2026',
    title: 'Perfil e Contatos — seletor de país no telefone + correções',
    items: [
      { type: 'new',         text: 'Campo de telefone e WhatsApp com seletor de país (bandeira + nome) em Perfil e Contatos' },
      { type: 'new',         text: 'Opção "Mesmo número do WhatsApp" sincroniza automaticamente os dois campos' },
      { type: 'improvement', text: 'Contato do próprio usuário exibe label "Usuário" em vez de "Cliente / Fornecedor"' },
      { type: 'fix',         text: 'Criação de compromisso inline via iframe funcionando corretamente em produção' },
    ],
  },
  {
    id: '2026-05-13-categorias-redesign',
    version: '0.2.6',
    date: '13/05/2026',
    title: 'Categorias — vínculos, transações e compromisso inline',
    items: [
      { type: 'new', text: 'Modal de compromisso abre na própria página de Categorias — sem navegar para outra tela' },
      { type: 'new', text: 'Coluna "Vínculos" exibe badges coloridos de projeto, dívida e compromisso com hover popup' },
      { type: 'new', text: 'Coluna "Transações" mostra contagem com hover popup das últimas 5 transações' },
      { type: 'new', text: 'Clicar no nome da subcategoria abre popup com todos os detalhes, vínculos, últimas transações e botão Editar' },
      { type: 'improvement', text: 'Ícone de editar removido das linhas de subcategoria — acesso via clique no nome' },
    ],
  },
  {
    id: '2026-05-10-login-redesign',
    version: '0.2.5',
    date: '10/05/2026',
    title: 'Tela de login — rodapé redesenhado',
    items: [
      { type: 'improvement', text: '"Esqueci minha senha" e "Ainda não tem conta?" separados em linhas próprias com divisor visual — fim da linha única apertada' },
    ],
  },
  {
    id: '2026-05-10-design-consistency',
    version: '0.2.4',
    date: '10/05/2026',
    title: 'Consistência visual e de interação em todo o sistema',
    items: [
      { type: 'improvement', text: 'Tags de transação agora recebem cores distintas por hash — cada tag tem sempre a mesma cor, sem repetição visual' },
      { type: 'improvement', text: 'Barra de filtros unificada em Compromissos, Pagamentos, Contatos e Relatórios — mesmo padrão visual de pills da página Contas' },
      { type: 'improvement', text: 'Toast de notificação: ícones SVG ilustrativos para sucesso, erro, aviso e informação' },
      { type: 'improvement', text: 'Botões "+ Novo" trocados para ícone SVG em todas as páginas — aparência consistente com o restante do sistema' },
      { type: 'improvement', text: 'Tipografia de cabeçalhos de tabela padronizada: tamanho xs, negrito, maiúsculas, espaçamento 0.05 em e cor secundária em todas as páginas' },
      { type: 'improvement', text: 'Primeira coluna congelada (sticky) ao rolar horizontalmente: Contas, Dívidas, Projetos e tabela agrupada de Compromissos' },
      { type: 'improvement', text: 'Tabela de Projetos agora rola horizontalmente em telas pequenas — sem corte de conteúdo' },
      { type: 'improvement', text: 'Tamanho e arredondamento de pills unificados em todo o sistema (padding 3 px × 8 px, border-radius full)' },
      { type: 'improvement', text: 'Utilitários CSS de campo: .field-group--2col, .field-group--3col, .field-group--val-moeda e .field-group--wide-narrow para layouts de formulário consistentes' },
      { type: 'fix',         text: 'Animação pulse-danger adicionada para alertas críticos de saldo negativo em Contas' },
    ],
  },
  {
    id: '2026-05-07-dividas-investimentos-rework',
    version: '0.2.3',
    date: '07/05/2026',
    title: 'Dívidas avançadas + Simulador de investimentos + Build com Vite',
    items: [
      { type: 'new',         text: 'Dívidas — regimes SAC, Price e Customizado (com fases jsonb): geração automática de tabela de amortização' },
      { type: 'new',         text: 'Dívidas — tipo de juros unificado: SELIC, SELIC+%, CDI, CDI+%, IPCA, IPCA+% (cotações ao vivo da BrasilAPI) ou manual fixo/variável' },
      { type: 'new',         text: 'Dívidas — histórico de mudanças de taxa quando o tipo é variável' },
      { type: 'new',         text: 'Dívidas — correção monetária mensal aplicada ao saldo (TR, IPCA, IGPM ou taxa fixa)' },
      { type: 'new',         text: 'Dívidas — status "Arquivada": ao excluir uma dívida com pagamentos, ela vai para o grupo Terminado preservando transações; restaurar recria o compromisso vinculado' },
      { type: 'new',         text: 'Investimentos — Simulador de juros compostos com 3 modos: saldo final, tempo necessário e aporte mensal (taxa SELIC ou manual)' },
      { type: 'new',         text: 'Investimentos — botão "+ Criar projeto com esses dados" no resultado do simulador, pré-preenchendo meta, saldo inicial e aporte' },
      { type: 'new',         text: 'Investimentos — opção "Criar compromisso vinculado" no Novo projeto, com valor, frequência, data do primeiro aporte e categoria' },
      { type: 'new',         text: 'Investimentos — fluxo de excluir/arquivar/restaurar projetos espelhando o de Dívidas (com aviso explicando o que será removido e mantido)' },
      { type: 'new',         text: 'Modal de novo contato unificado — mesma janela em Dívidas, Investimentos, Transações e Contatos (sem divergências de UX)' },
      { type: 'improvement', text: 'Formato de número padronizado em todo o sistema: vírgula como separador decimal, ponto como milhar' },
      { type: 'improvement', text: 'Painel Admin — fluxo de aprovação de strings: botão "Aprovar" agora salva, aprova e fecha o modal em um clique' },
      { type: 'improvement', text: 'Build com Vite: site em produção agora carrega 1 bundle por página em vez de 30+ arquivos separados — carregamento mais rápido' },
      { type: 'fix',         text: 'Diversas correções menores em validações e mensagens de erro identificadas durante auditoria de código' },
    ],
  },
  {
    id: '2026-05-05-transferencias-cambio',
    version: '0.2.2',
    date: '05/05/2026',
    title: 'Transferências entre contas com câmbio',
    items: [
      { type: 'new',         text: 'Transferências entre contas criam automaticamente dois registros vinculados — saída e entrada — garantindo balanço correto por conta' },
      { type: 'new',         text: 'Câmbio automático em transferências estrangeiras: cotação do dia preenchida na abertura, valor previsto calculado (bloqueado) e valor recebido real editável' },
      { type: 'new',         text: 'Contas: toggle Nacional / Estrangeira — Real selecionado automaticamente para contas nacionais; moeda configurável para estrangeiras' },
      { type: 'new',         text: 'Badge de moeda nos cards de contas — BRL cinza para nacionais, moeda estrangeira em roxo' },
      { type: 'new',         text: 'Tabela de transações: coluna Conta exibe fluxo "Origem → Destino"; badge "Transferência" na coluna Categoria; indicador "saída / entrada" na Subcategoria' },
      { type: 'improvement', text: 'Campos Bloco, Categoria, Subcategoria e Cliente/Fornecedor ficam desabilitados ao selecionar tipo Transferência' },
      { type: 'improvement', text: 'Admin — Strings de idioma: grupos "Para Aprovação" e "Aprovados", badges de estado (virgem/atualizada), data e hora de cada alteração, botão de aprovação individual' },
      { type: 'fix',         text: 'Descrição de conta: quebras de linha e bullet points agora exibidos corretamente nos detalhes' },
      { type: 'fix',         text: 'Painel Admin — Usuários: contagem de usuários voltou a carregar corretamente' },
    ],
  },
  {
    id: '2026-05-05-mobile-contatos',
    version: '0.2.0',
    date: '05/05/2026',
    title: 'Contatos redesenhado + navegação mobile',
    items: [
      { type: 'new',         text: 'Navegação mobile: botão hambúrguer abre sidebar deslizante com overlay em todas as páginas' },
      { type: 'new',         text: 'Busca por CNPJ via Brasil API — preenche nome, endereço, telefone, e-mail e logo automaticamente' },
      { type: 'new',         text: 'Logo automático de empresas via Clearbit (a partir do domínio do e-mail ou website)' },
      { type: 'new',         text: 'Seletor de contato com busca em tempo real e detecção de duplicatas em todas as páginas' },
      { type: 'new',         text: 'Aba Vínculos nos detalhes do contato — lista dívidas e projetos de investimento vinculados' },
      { type: 'new',         text: 'Novos campos: tipo (Pessoa Física / Empresa), WhatsApp, Website, LinkedIn, Instagram, Aniversário, Empresa e Cargo' },
      { type: 'new',         text: 'Cartela de 21 cores unificada em Contas, Categorias e Projetos' },
      { type: 'improvement', text: 'Filtros por relação (Cliente / Fornecedor / Arquivados) e tipo (Pessoas / Empresas) com contagem' },
      { type: 'improvement', text: 'Lista de contatos com cabeçalhos fixos por letra e badges C / F por tipo de relação' },
      { type: 'improvement', text: 'Modais em bottom-sheet no mobile e campos de formulário em coluna única' },
      { type: 'fix',         text: 'Corrigido erro que impedia o carregamento da página Contatos' },
    ],
  },
  {
    id: '2026-05-04-feedback-engine',
    version: '0.1.9',
    date: '04/05/2026',
    title: 'Feedback Engine + refinamento de Categorias',
    items: [
      { type: 'new',         text: 'Feedback Engine: página logada (/feedback), form público (/feedback-publico) e painel admin com 3 views — Triagem, Em andamento e Arquivo' },
      { type: 'new',         text: '6 tipos de feedback com cor + ícone — Bug, Sugestão, Funcionalidade, Pergunta, Elogio, Parceria' },
      { type: 'new',         text: 'Integração com Novidades — seção "No forno" mostra itens em progresso, e cada release lista os feedbacks que atendeu' },
      { type: 'new',         text: 'Item "Ajuda & Sugestões" no menu do avatar' },
      { type: 'new',         text: 'Drag & drop pra reordenar categorias dentro dos blocos em Configurações' },
      { type: 'new',         text: 'Coluna Vínculo nas categorias com 3 níveis (projeto/dívida → "com transações" → "sem vínculo")' },
      { type: 'new',         text: 'Coluna Descrição em categorias e subcategorias, com popover de detalhes ao passar o mouse' },
      { type: 'new',         text: 'Banner sticky empilhável dos blocos (CONTRIBUIÇÃO, SONHOS, CUSTO DE VIDA) ao rolar a lista' },
      { type: 'improvement', text: 'Categoria com histórico exige confirmação explícita pra mudar de bloco' },
      { type: 'improvement', text: 'Botões "+" SVG inline nos headings de Categoria/Subcategoria, por bloco' },
      { type: 'fix',         text: 'Sticky do menu interno de Configurações agora funciona corretamente ao rolar' },
    ],
  },
  {
    id: '2026-05-05-cat-click-modal',
    version: '0.1.8',
    date: '05/05/2026',
    title: 'Atalho de categoria para novo compromisso',
    items: [
      { type: 'improvement', text: 'Clicar em uma categoria sem subcategorias abre diretamente o modal de novo compromisso com a categoria já pré-selecionada' },
    ],
  },
  {
    id: '2026-05-05-tabela-plana',
    version: '0.1.7',
    date: '05/05/2026',
    title: 'Tabela plana — Categoria, Subcategoria e filtro Sem compromisso',
    items: [
      { type: 'new',         text: 'Tabela de Compromissos agora exibe tudo em lista plana com colunas Categoria e Subcategoria — sem headings de grupo' },
      { type: 'new',         text: 'Filtro "Sem compromisso": mostra categorias e subcategorias criadas em Configurações que ainda não têm valor definido' },
      { type: 'improvement', text: 'Categorias folha (sem subcategorias) aparecem automaticamente na tabela — basta criar a categoria em Configurações' },
    ],
  },
  {
    id: '2026-05-05-cat-modal-toggle',
    version: '0.1.6',
    date: '05/05/2026',
    title: 'Compromisso direto em categoria — via modal',
    items: [
      { type: 'new',         text: 'Toggle "Nova subcategoria / Categoria existente" no modal de Novo Compromisso — selecione uma categoria já existente (ex: Jhow Silva) e defina valor, tipo, dívida e conta direto, sem criar subcategorias' },
      { type: 'improvement', text: 'Categoria com compromisso direto aparece como linha normal na tabela, sem badge especial' },
      { type: 'improvement', text: 'Clicar na linha abre o modal de edição no modo correto para alterar os dados' },
    ],
  },
  {
    id: '2026-05-05-cat-valor-direto',
    version: '0.1.5',
    date: '05/05/2026',
    title: 'Compromissos diretos em categorias',
    items: [
      { type: 'new',         text: 'Categorias agora podem ter um valor de compromisso direto, sem precisar criar subcategorias — ideal para pagamentos únicos como salários e serviços por pessoa' },
    ],
  },
  {
    id: '2026-05-05-btn-salvar',
    version: '0.1.4',
    date: '05/05/2026',
    title: 'Correção — botão Salvar desabilitado após primeiro cadastro',
    items: [
      { type: 'fix', text: 'Botão Salvar ficava desabilitado após o primeiro cadastro bem-sucedido em Contas, Investimentos, Transações e Compromissos — era necessário recarregar a página para cadastrar novamente' },
    ],
  },
  {
    id: '2026-05-05-compromissos-blocos',
    version: '0.1.3',
    date: '05/05/2026',
    title: 'Organização por blocos — Compromissos',
    items: [
      { type: 'improvement', text: 'Compromissos agora exibe os lançamentos organizados nos 3 blocos principais: Contribuição, Sonhos e Custo de vida — igual às demais páginas' },
    ],
  },
  {
    id: '2026-05-04-novidades',
    version: '0.1.2',
    date: '04/05/2026',
    title: 'Página Novidades com badge numérico',
    items: [
      { type: 'new',         text: 'Página dedicada "Novidades" no menu lateral com registro de todas as versões publicadas' },
      { type: 'new',         text: 'Badge numérico vermelho no ícone de Novidades indicando quantas versões não foram lidas' },
      { type: 'improvement', text: 'Badge some automaticamente ao visitar a página de Novidades' },
    ],
  },
  {
    id: '2026-05-04-b2fab70',
    version: '0.1.1',
    date: '04/05/2026',
    title: 'Correção de layout — Investimentos',
    items: [
      { type: 'fix', text: 'Botão Salvar e rodapé do modal de Novo Projeto em Investimentos estavam ocultos em telas com altura reduzida' },
    ],
  },
  {
    id: '2026-05-03-fbcc0c4',
    version: '0.1.0',
    date: '03/05/2026',
    title: 'Auditoria de código — 38 melhorias',
    items: [
      { type: 'new',         text: 'Toggle de mostrar/ocultar senha no formulário de cadastro' },
      { type: 'new',         text: 'Exportação de Excel agora gera arquivo .xlsx real via SheetJS' },
      { type: 'improvement', text: 'Utilitários centralizados — formatação de datas, escape HTML e outros agora consistentes em todo o sistema' },
      { type: 'improvement', text: 'Visibilidade de colunas em Transações migrada para o sistema compartilhado' },
      { type: 'improvement', text: 'Caixas de confirmação substituídas por diálogo visual (em vez de popup nativo do navegador)' },
      { type: 'improvement', text: 'Links de navegação corrigidos para caminhos absolutos' },
      { type: 'improvement', text: 'Acessibilidade aprimorada em Contas (navegação por teclado) e Orçamento (labels para leitores de tela)' },
      { type: 'fix',         text: 'Listeners de eventos duplicados removidos em menu de usuário e visibilidade de colunas' },
      { type: 'fix',         text: 'Tela de login sempre visível mesmo quando ocorre erro de autenticação' },
    ],
  },
];
