// =============================================================
// FinFlow — Registro de versões
// Adicione entradas novas no INÍCIO do array.
// id deve ser único — é usado para rastrear o que o usuário já leu.
// type: 'new' | 'fix' | 'improvement'
// =============================================================

export const CHANGELOG = [
  {
    id: '2026-05-07-dividas-investimentos-rework',
    version: '0.2.3',
    date: '07/05/2026',
    title: 'Dívidas avançadas + Simulador de investimentos + Build com Vite',
    items: [
      { type: 'new',         text: 'Dívidas — regimes SAC, Price e Customizado (com fases jsonb): geração automática de tabela de amortização' },
      { type: 'new',         text: 'Dívidas — tipo de juros unificado: SELIC, SELIC+%, CDI, CDI+%, IPCA, IPCA+% (cotações ao vivo da BrasilAPI) ou manual fixo/variável' },
      { type: 'new',         text: 'Dívidas — histórico de mudanças de taxa quando o tipo é variável' },
      { type: 'new',         text: 'Dívidas — correção monetária mensal aplicada ao saldo (TR, IPCA, IGPM ou taxa fixa)' },
      { type: 'new',         text: 'Dívidas — status "Arquivada": ao excluir uma dívida com pagamentos, ela vai para o grupo Terminado preservando transações; restaurar recria o compromisso vinculado' },
      { type: 'new',         text: 'Investimentos — Simulador de juros compostos com 3 modos: saldo final, tempo necessário e aporte mensal (taxa SELIC ou manual)' },
      { type: 'new',         text: 'Investimentos — botão "+ Criar projeto com esses dados" no resultado do simulador, pré-preenchendo meta, saldo inicial e aporte' },
      { type: 'new',         text: 'Investimentos — opção "Criar compromisso vinculado" no Novo projeto, com valor, frequência, data do primeiro aporte e categoria' },
      { type: 'new',         text: 'Investimentos — fluxo de excluir/arquivar/restaurar projetos espelhando o de Dívidas (com aviso explicando o que será removido e mantido)' },
      { type: 'new',         text: 'Modal de novo contato unificado — mesma janela em Dívidas, Investimentos, Transações e Contatos (sem divergências de UX)' },
      { type: 'improvement', text: 'Formato de número padronizado em todo o sistema: vírgula como separador decimal, ponto como milhar' },
      { type: 'improvement', text: 'Painel Admin — fluxo de aprovação de strings: botão "Aprovar" agora salva, aprova e fecha o modal em um clique' },
      { type: 'improvement', text: 'Build com Vite: site em produção agora carrega 1 bundle por página em vez de 30+ arquivos separados — carregamento mais rápido' },
      { type: 'fix',         text: 'Diversas correções menores em validações e mensagens de erro identificadas durante auditoria de código' },
    ],
  },
  {
    id: '2026-05-05-transferencias-cambio',
    version: '0.2.2',
    date: '05/05/2026',
    title: 'Transferências entre contas com câmbio',
    items: [
      { type: 'new',         text: 'Transferências entre contas criam automaticamente dois registros vinculados — saída e entrada — garantindo balanço correto por conta' },
      { type: 'new',         text: 'Câmbio automático em transferências estrangeiras: cotação do dia preenchida na abertura, valor previsto calculado (bloqueado) e valor recebido real editável' },
      { type: 'new',         text: 'Contas: toggle Nacional / Estrangeira — Real selecionado automaticamente para contas nacionais; moeda configurável para estrangeiras' },
      { type: 'new',         text: 'Badge de moeda nos cards de contas — BRL cinza para nacionais, moeda estrangeira em roxo' },
      { type: 'new',         text: 'Tabela de transações: coluna Conta exibe fluxo "Origem → Destino"; badge "Transferência" na coluna Categoria; indicador "saída / entrada" na Subcategoria' },
      { type: 'improvement', text: 'Campos Bloco, Categoria, Subcategoria e Cliente/Fornecedor ficam desabilitados ao selecionar tipo Transferência' },
      { type: 'improvement', text: 'Admin — Strings de idioma: grupos "Para Aprovação" e "Aprovados", badges de estado (virgem/atualizada), data e hora de cada alteração, botão de aprovação individual' },
      { type: 'fix',         text: 'Descrição de conta: quebras de linha e bullet points agora exibidos corretamente nos detalhes' },
      { type: 'fix',         text: 'Painel Admin — Usuários: contagem de usuários voltou a carregar corretamente' },
    ],
  },
  {
    id: '2026-05-05-mobile-contatos',
    version: '0.2.0',
    date: '05/05/2026',
    title: 'Contatos redesenhado + navegação mobile',
    items: [
      { type: 'new',         text: 'Navegação mobile: botão hambúrguer abre sidebar deslizante com overlay em todas as páginas' },
      { type: 'new',         text: 'Busca por CNPJ via Brasil API — preenche nome, endereço, telefone, e-mail e logo automaticamente' },
      { type: 'new',         text: 'Logo automático de empresas via Clearbit (a partir do domínio do e-mail ou website)' },
      { type: 'new',         text: 'Seletor de contato com busca em tempo real e detecção de duplicatas em todas as páginas' },
      { type: 'new',         text: 'Aba Vínculos nos detalhes do contato — lista dívidas e projetos de investimento vinculados' },
      { type: 'new',         text: 'Novos campos: tipo (Pessoa Física / Empresa), WhatsApp, Website, LinkedIn, Instagram, Aniversário, Empresa e Cargo' },
      { type: 'new',         text: 'Cartela de 21 cores unificada em Contas, Categorias e Projetos' },
      { type: 'improvement', text: 'Filtros por relação (Cliente / Fornecedor / Arquivados) e tipo (Pessoas / Empresas) com contagem' },
      { type: 'improvement', text: 'Lista de contatos com cabeçalhos fixos por letra e badges C / F por tipo de relação' },
      { type: 'improvement', text: 'Modais em bottom-sheet no mobile e campos de formulário em coluna única' },
      { type: 'fix',         text: 'Corrigido erro que impedia o carregamento da página Contatos' },
    ],
  },
  {
    id: '2026-05-04-feedback-engine',
    version: '0.1.9',
    date: '04/05/2026',
    title: 'Feedback Engine + refinamento de Categorias',
    items: [
      { type: 'new',         text: 'Feedback Engine: página logada (/feedback), form público (/feedback-publico) e painel admin com 3 views — Triagem, Em andamento e Arquivo' },
      { type: 'new',         text: '6 tipos de feedback com cor + ícone — Bug, Sugestão, Funcionalidade, Pergunta, Elogio, Parceria' },
      { type: 'new',         text: 'Integração com Novidades — seção "No forno" mostra itens em progresso, e cada release lista os feedbacks que atendeu' },
      { type: 'new',         text: 'Item "Ajuda & Sugestões" no menu do avatar' },
      { type: 'new',         text: 'Drag & drop pra reordenar categorias dentro dos blocos em Configurações' },
      { type: 'new',         text: 'Coluna Vínculo nas categorias com 3 níveis (projeto/dívida → "com transações" → "sem vínculo")' },
      { type: 'new',         text: 'Coluna Descrição em categorias e subcategorias, com popover de detalhes ao passar o mouse' },
      { type: 'new',         text: 'Banner sticky empilhável dos blocos (CONTRIBUIÇÃO, SONHOS, CUSTO DE VIDA) ao rolar a lista' },
      { type: 'improvement', text: 'Categoria com histórico exige confirmação explícita pra mudar de bloco' },
      { type: 'improvement', text: 'Botões "+" SVG inline nos headings de Categoria/Subcategoria, por bloco' },
      { type: 'fix',         text: 'Sticky do menu interno de Configurações agora funciona corretamente ao rolar' },
    ],
  },
  {
    id: '2026-05-05-cat-click-modal',
    version: '0.1.8',
    date: '05/05/2026',
    title: 'Atalho de categoria para novo compromisso',
    items: [
      { type: 'improvement', text: 'Clicar em uma categoria sem subcategorias abre diretamente o modal de novo compromisso com a categoria já pré-selecionada' },
    ],
  },
  {
    id: '2026-05-05-tabela-plana',
    version: '0.1.7',
    date: '05/05/2026',
    title: 'Tabela plana — Categoria, Subcategoria e filtro Sem compromisso',
    items: [
      { type: 'new',         text: 'Tabela de Compromissos agora exibe tudo em lista plana com colunas Categoria e Subcategoria — sem headings de grupo' },
      { type: 'new',         text: 'Filtro "Sem compromisso": mostra categorias e subcategorias criadas em Configurações que ainda não têm valor definido' },
      { type: 'improvement', text: 'Categorias folha (sem subcategorias) aparecem automaticamente na tabela — basta criar a categoria em Configurações' },
    ],
  },
  {
    id: '2026-05-05-cat-modal-toggle',
    version: '0.1.6',
    date: '05/05/2026',
    title: 'Compromisso direto em categoria — via modal',
    items: [
      { type: 'new',         text: 'Toggle "Nova subcategoria / Categoria existente" no modal de Novo Compromisso — selecione uma categoria já existente (ex: Jhow Silva) e defina valor, tipo, dívida e conta direto, sem criar subcategorias' },
      { type: 'improvement', text: 'Categoria com compromisso direto aparece como linha normal na tabela, sem badge especial' },
      { type: 'improvement', text: 'Clicar na linha abre o modal de edição no modo correto para alterar os dados' },
    ],
  },
  {
    id: '2026-05-05-cat-valor-direto',
    version: '0.1.5',
    date: '05/05/2026',
    title: 'Compromissos diretos em categorias',
    items: [
      { type: 'new',         text: 'Categorias agora podem ter um valor de compromisso direto, sem precisar criar subcategorias — ideal para pagamentos únicos como salários e serviços por pessoa' },
    ],
  },
  {
    id: '2026-05-05-btn-salvar',
    version: '0.1.4',
    date: '05/05/2026',
    title: 'Correção — botão Salvar desabilitado após primeiro cadastro',
    items: [
      { type: 'fix', text: 'Botão Salvar ficava desabilitado após o primeiro cadastro bem-sucedido em Contas, Investimentos, Transações e Compromissos — era necessário recarregar a página para cadastrar novamente' },
    ],
  },
  {
    id: '2026-05-05-compromissos-blocos',
    version: '0.1.3',
    date: '05/05/2026',
    title: 'Organização por blocos — Compromissos',
    items: [
      { type: 'improvement', text: 'Compromissos agora exibe os lançamentos organizados nos 3 blocos principais: Contribuição, Sonhos e Custo de vida — igual às demais páginas' },
    ],
  },
  {
    id: '2026-05-04-novidades',
    version: '0.1.2',
    date: '04/05/2026',
    title: 'Página Novidades com badge numérico',
    items: [
      { type: 'new',         text: 'Página dedicada "Novidades" no menu lateral com registro de todas as versões publicadas' },
      { type: 'new',         text: 'Badge numérico vermelho no ícone de Novidades indicando quantas versões não foram lidas' },
      { type: 'improvement', text: 'Badge some automaticamente ao visitar a página de Novidades' },
    ],
  },
  {
    id: '2026-05-04-b2fab70',
    version: '0.1.1',
    date: '04/05/2026',
    title: 'Correção de layout — Investimentos',
    items: [
      { type: 'fix', text: 'Botão Salvar e rodapé do modal de Novo Projeto em Investimentos estavam ocultos em telas com altura reduzida' },
    ],
  },
  {
    id: '2026-05-03-fbcc0c4',
    version: '0.1.0',
    date: '03/05/2026',
    title: 'Auditoria de código — 38 melhorias',
    items: [
      { type: 'new',         text: 'Toggle de mostrar/ocultar senha no formulário de cadastro' },
      { type: 'new',         text: 'Exportação de Excel agora gera arquivo .xlsx real via SheetJS' },
      { type: 'improvement', text: 'Utilitários centralizados — formatação de datas, escape HTML e outros agora consistentes em todo o sistema' },
      { type: 'improvement', text: 'Visibilidade de colunas em Transações migrada para o sistema compartilhado' },
      { type: 'improvement', text: 'Caixas de confirmação substituídas por diálogo visual (em vez de popup nativo do navegador)' },
      { type: 'improvement', text: 'Links de navegação corrigidos para caminhos absolutos' },
      { type: 'improvement', text: 'Acessibilidade aprimorada em Contas (navegação por teclado) e Orçamento (labels para leitores de tela)' },
      { type: 'fix',         text: 'Listeners de eventos duplicados removidos em menu de usuário e visibilidade de colunas' },
      { type: 'fix',         text: 'Tela de login sempre visível mesmo quando ocorre erro de autenticação' },
    ],
  },
];
